grafana/k8s-monitoring-helm

README.md, charts/k8s-monitoring/Chart.yaml, charts/k8s-monitoring/README.md, charts/k8s-monitoring/README.md.gotmpl, charts/k8s-monitoring/templates/agent_config/_cadvisor.river.txt, charts/k8s-monitoring/templates/agent_config/_kube_state_metrics.river.txt, charts/k8s-monitoring/templates/agent_config/_kubelet.river.txt, charts/k8s-monitoring/templates/agent_config/_node_exporter.river.txt, charts/k8s-monitoring/templates/agent_config/_opencost.txt, tests/Makefile, tests/custom-allow-lists/output.yaml, tests/custom-allow-lists/values.yaml, tests/no-allow-lists/output.yaml, tests/no-allow-lists/values.yaml
If no allow list is wanted, don't waste the step with the relabel component.
=> Make the allow list more sensible to work with.

charts/k8s-monitoring/Chart.yaml, charts/k8s-monitoring/README.md, charts/k8s-monitoring/templates/agent_config/_cluster_events.river.txt, charts/k8s-monitoring/templates/agent_config/_loki.river.txt, charts/k8s-monitoring/templates/agent_config/_pod_logs.river.txt, tests/default-values/output.yaml, tests/logs-only/output.yaml, tests/openshift-compatible/output.yaml
=> Add relabeling rules to pod logs

CODEOWNERS, README.md, charts/k8s-monitoring/Chart.yaml, charts/k8s-monitoring/README.md
👋 Adding myself as a maintainer.
=> Add skl as a maintainer

charts/k8s-monitoring/templates/credentials.yaml, tests/default-values/values.yaml
=> Force usernames and passwords to strings before encoding them

charts/k8s-monitoring/README.md, charts/k8s-monitoring/README.md.gotmpl
=> Fix OpenShift docs

charts/k8s-monitoring/Chart.yaml, charts/k8s-monitoring/README.md, charts/k8s-monitoring/templates/agent_config/_loki.river.txt, charts/k8s-monitoring/templates/agent_config/_prometheus.river.txt, charts/k8s-monitoring/templates/credentials.yaml, charts/k8s-monitoring/values.yaml, examples/custom-allow-lists/output.yaml, examples/custom-allow-lists/values.yaml, examples/custom-config/output.yaml, examples/custom-config/values.yaml, examples/default-values/output.yaml, examples/default-values/values.yaml, examples/logs-only/values.yaml, examples/metrics-only/output.yaml, examples/metrics-only/values.yaml, examples/openshift-compatible/output.yaml, examples/openshift-compatible/values.yaml, examples/windows-exporter/output.yaml, examples/windows-exporter/values.yaml
Also makes usernames and passwords optional.
Fixes #52
=> Put prometheus and loki auth under the basicAuth object

charts/k8s-monitoring/Chart.yaml, charts/k8s-monitoring/README.md, charts/k8s-monitoring/README.md.gotmpl, charts/k8s-monitoring/templates/agent_config/_agent.river.txt, charts/k8s-monitoring/templates/agent_config/_cadvisor.river.txt, charts/k8s-monitoring/templates/agent_config/_cluster_events.river.txt, charts/k8s-monitoring/templates/agent_config/_cluster_name.river.txt, charts/k8s-monitoring/templates/agent_config/_kube_state_metrics.river.txt, charts/k8s-monitoring/templates/agent_config/_kubelet.river.txt, charts/k8s-monitoring/templates/agent_config/_node_exporter.river.txt, charts/k8s-monitoring/templates/agent_config/_opencost.txt, charts/k8s-monitoring/templates/agent_config/_pod_logs.river.txt, charts/k8s-monitoring/templates/agent_config/_windows_exporter.river.txt, charts/k8s-monitoring/templates/grafana-agent-config.yaml, examples/custom-allow-lists/output.yaml, examples/custom-config/output.yaml, examples/default-values/output.yaml, examples/logs-only/output.yaml, examples/metrics-only/output.yaml, examples/openshift-compatible/output.yaml, examples/windows-exporter/output.yaml
This removes it from the configuration ConfigMap, simplifying it.
=> Inline the cluster name

charts/k8s-monitoring/Chart.lock, charts/k8s-monitoring/Chart.yaml, charts/k8s-monitoring/README.md, charts/k8s-monitoring/templates/agent_config/_pod_monitors.txt, charts/k8s-monitoring/templates/agent_config/_service_monitors.txt, examples/custom-allow-lists/metrics.river, examples/custom-allow-lists/output.yaml, examples/custom-config/metrics.river, examples/custom-config/output.yaml, examples/default-values/metrics.river, examples/default-values/output.yaml, examples/metrics-only/metrics.river, examples/metrics-only/output.yaml, examples/openshift-compatible/metrics.river, examples/openshift-compatible/output.yaml, examples/otel-collector/metrics.river, examples/otel-collector/output.yaml, examples/windows-exporter/metrics.river, examples/windows-exporter/output.yaml
=> Add cluster label step for PodMonitors and ServiceMonitors

charts/k8s-monitoring/Chart.yaml, charts/k8s-monitoring/README.md, charts/k8s-monitoring/templates/agent_config/_cadvisor.river.txt, charts/k8s-monitoring/templates/agent_config/_kubelet.river.txt, charts/k8s-monitoring/values.yaml
=> Make the Kubernetes API service configurable

README.md, charts/k8s-monitoring/Chart.yaml, charts/k8s-monitoring/README.md, charts/k8s-monitoring/templates/grafana-agent-logs-config.yaml, charts/k8s-monitoring/values.yaml, examples/custom-config/logs.river, examples/custom-config/metrics.river, examples/custom-config/output.yaml, examples/custom-config/values.yaml
=> Adds `extraConfig` value to logs config

charts/k8s-monitoring/Chart.yaml, charts/k8s-monitoring/README.md, charts/k8s-monitoring/templates/agent_config/_cadvisor.river.txt, charts/k8s-monitoring/templates/agent_config/_kube_state_metrics.river.txt, charts/k8s-monitoring/templates/agent_config/_kubelet.river.txt, charts/k8s-monitoring/templates/agent_config/_node_exporter.river.txt, charts/k8s-monitoring/templates/agent_config/_opencost.txt, charts/k8s-monitoring/templates/agent_config/_windows_exporter.river.txt, charts/k8s-monitoring/values.yaml, examples/custom-allow-lists/README.md, examples/custom-config/README.md, examples/custom-config/logs.river, examples/custom-config/values.yaml, examples/default-values/README.md, examples/extra-rules/README.md, examples/extra-rules/logs.river, examples/extra-rules/metrics.river, examples/extra-rules/output.yaml, examples/extra-rules/values.yaml, examples/logs-only/README.md, examples/metrics-only/README.md, examples/openshift-compatible/README.md, examples/windows-exporter/README.md
* Allow for extra relabeling and metric relabeling rules for every metric source.
* Allow for extra relabeling rules and processing stages for pod logs 
* Update example READMEs
=> Feat: Allow for extra rules and stages

charts/k8s-monitoring/Chart.yaml, charts/k8s-monitoring/README.md, charts/k8s-monitoring/templates/agent_config/_cadvisor.river.txt, charts/k8s-monitoring/templates/agent_config/_kube_state_metrics.river.txt, charts/k8s-monitoring/templates/agent_config/_kubelet.river.txt, charts/k8s-monitoring/templates/agent_config/_node_exporter.river.txt, charts/k8s-monitoring/templates/agent_config/_opencost.txt, charts/k8s-monitoring/templates/agent_config/_pod_monitors.txt, charts/k8s-monitoring/templates/agent_config/_prometheus.river.txt, charts/k8s-monitoring/templates/agent_config/_service_monitors.txt, charts/k8s-monitoring/values.yaml, examples/custom-allow-lists/metrics.river, examples/custom-allow-lists/output.yaml, examples/custom-config/metrics.river, examples/custom-config/output.yaml, examples/default-values/metrics.river, examples/default-values/output.yaml, examples/extra-rules/metrics.river, examples/extra-rules/output.yaml, examples/extra-rules/values.yaml, examples/metrics-only/metrics.river, examples/metrics-only/output.yaml, examples/openshift-compatible/metrics.river, examples/openshift-compatible/output.yaml, examples/windows-exporter/metrics.river, examples/windows-exporter/output.yaml
also fix PodMonitor and ServiceMonitor so they get the extraMetricRelabelingRules
=> Add write_relabel_config

charts/k8s-monitoring/Chart.yaml, charts/k8s-monitoring/README.md, charts/k8s-monitoring/templates/agent_config/_cadvisor.river.txt, charts/k8s-monitoring/templates/agent_config/_kube_state_metrics.river.txt, charts/k8s-monitoring/templates/agent_config/_kubelet.river.txt, charts/k8s-monitoring/templates/agent_config/_node_exporter.river.txt, charts/k8s-monitoring/templates/agent_config/_opencost.txt, charts/k8s-monitoring/templates/agent_config/_windows_exporter.river.txt, charts/k8s-monitoring/values.yaml, examples/custom-allow-lists/metrics.river, examples/custom-config/metrics.river, examples/custom-config/output.yaml, examples/default-values/output.yaml, examples/extra-rules/metrics.river, examples/extra-rules/output.yaml, examples/metrics-only/metrics.river, examples/metrics-only/output.yaml, examples/openshift-compatible/metrics.river, examples/openshift-compatible/output.yaml, examples/scrape-intervals/README.md, examples/scrape-intervals/metrics.river, examples/scrape-intervals/output.yaml, examples/scrape-intervals/values.yaml, examples/windows-exporter/metrics.river, examples/windows-exporter/output.yaml
=> Add scrape interval to all metric sources

charts/k8s-monitoring/README.md, charts/k8s-monitoring/templates/agent_config/_pod_logs.river.txt, charts/k8s-monitoring/values.yaml, examples/custom-config/logs.river, examples/custom-config/output.yaml, examples/default-values/logs.river, examples/default-values/output.yaml, examples/extra-rules/logs.river, examples/extra-rules/output.yaml, examples/logs-only/logs.river, examples/logs-only/output.yaml, examples/openshift-compatible/logs.river, examples/openshift-compatible/output.yaml, examples/specific-namespace/logs.river, examples/specific-namespace/output.yaml, examples/traces-enabled/logs.river, examples/traces-enabled/output.yaml, examples/windows-exporter/logs.river, examples/windows-exporter/output.yaml
=> Logging improvements

charts/k8s-monitoring/templates/_helpers.tpl, charts/k8s-monitoring/templates/agent_config/_kubernetes_monitoring_telemetry.river.txt, charts/k8s-monitoring/templates/kubernetes-monitoring-telemetry.yaml, examples/custom-allow-lists/metrics.river, examples/custom-allow-lists/output.yaml, examples/custom-config/metrics.river, examples/custom-config/output.yaml, examples/default-values/metrics.river, examples/default-values/output.yaml, examples/extra-rules/metrics.river, examples/extra-rules/output.yaml, examples/logs-only/output.yaml, examples/metrics-only/metrics.river, examples/metrics-only/output.yaml, examples/openshift-compatible/metrics.river, examples/openshift-compatible/output.yaml, examples/private-image-registry/metrics.river, examples/private-image-registry/output.yaml, examples/scrape-intervals/metrics.river, examples/scrape-intervals/output.yaml, examples/specific-namespace/metrics.river, examples/specific-namespace/output.yaml, examples/traces-enabled/metrics.river, examples/traces-enabled/output.yaml, examples/windows-exporter/metrics.river, examples/windows-exporter/output.yaml
=> Update static metric to include name, namespace, extraConfigs, and job label

charts/k8s-monitoring/README.md, charts/k8s-monitoring/templates/grafana-agent-logs-rbac.yaml, charts/k8s-monitoring/templates/grafana-agent-rbac.yaml, charts/k8s-monitoring/templates/platform_specific/openshift/security-context-constraint.yaml, charts/k8s-monitoring/values.yaml, examples/custom-allow-lists/output.yaml, examples/custom-config/output.yaml, examples/default-values/output.yaml, examples/extra-rules/output.yaml, examples/logs-only/output.yaml, examples/metrics-only/output.yaml, examples/openshift-compatible/README.md, examples/openshift-compatible/output.yaml, examples/openshift-compatible/values.yaml, examples/private-image-registry/output.yaml, examples/scrape-intervals/output.yaml, examples/specific-namespace/output.yaml, examples/traces-enabled/output.yaml, examples/windows-exporter/output.yaml
=> Fixes for OpenShift

charts/k8s-monitoring/templates/agent_config/_traces.river.txt, examples/traces-enabled/metrics.river, examples/traces-enabled/output.yaml
This enables navigation from app o11y to k8s monitoring.
=> Add k8s.cluster.name semantic attribute

charts/k8s-monitoring/README.md, charts/k8s-monitoring/ci/ci-values.yaml, charts/k8s-monitoring/ci/otlp-metrics-service-values.yaml, charts/k8s-monitoring/templates/_helpers.tpl, charts/k8s-monitoring/templates/agent_config/_traces.river.txt, charts/k8s-monitoring/templates/agent_config/_traces_service.river.txt, charts/k8s-monitoring/values.yaml, examples/control-plane-metrics/output.yaml, examples/custom-allow-lists/output.yaml, examples/custom-config/output.yaml, examples/default-values/output.yaml, examples/eks-fargate/output.yaml, examples/extra-rules/output.yaml, examples/gke-autopilot/output.yaml, examples/logs-only/output.yaml, examples/metrics-only/output.yaml, examples/openshift-compatible/output.yaml, examples/otel-metrics-service/output.yaml, examples/private-image-registry/output.yaml, examples/scrape-intervals/output.yaml, examples/specific-namespace/output.yaml, examples/traces-enabled/output.yaml, examples/windows-exporter/output.yaml
=> Add a protocol field for tempo to be able to switch between otlp and otlphttp

charts/k8s-monitoring/values.yaml, examples/control-plane-metrics/output.yaml, examples/custom-allow-lists/output.yaml, examples/custom-config/output.yaml, examples/default-values/output.yaml, examples/eks-fargate/output.yaml, examples/extra-rules/output.yaml, examples/gke-autopilot/output.yaml, examples/metrics-only/output.yaml, examples/openshift-compatible/output.yaml, examples/otel-metrics-service/output.yaml, examples/private-image-registry/output.yaml, examples/scrape-intervals/output.yaml, examples/specific-namespace/output.yaml, examples/traces-enabled/output.yaml, examples/windows-exporter/output.yaml
=> Set CURRENT_CLUSTER_ID_FILTER_ENABLED to enable the cluster filter in OpenCost queries

charts/k8s-monitoring/templates/agent_config/_pod_logs.river.txt, examples/control-plane-metrics/logs.river, examples/control-plane-metrics/output.yaml, examples/custom-config/logs.river, examples/custom-config/output.yaml, examples/default-values/logs.river, examples/default-values/output.yaml, examples/extra-rules/logs.river, examples/extra-rules/output.yaml, examples/gke-autopilot/logs.river, examples/gke-autopilot/output.yaml, examples/logs-only/logs.river, examples/logs-only/output.yaml, examples/openshift-compatible/logs.river, examples/openshift-compatible/output.yaml, examples/otel-metrics-service/logs.river, examples/otel-metrics-service/output.yaml, examples/private-image-registry/logs.river, examples/private-image-registry/output.yaml, examples/proxies/logs.river, examples/proxies/output.yaml, examples/specific-namespace/logs.river, examples/specific-namespace/output.yaml, examples/traces-enabled/logs.river, examples/traces-enabled/output.yaml, examples/windows-exporter/logs.river, examples/windows-exporter/output.yaml
=> Remove the filename label from logs

charts/k8s-monitoring/README.md, charts/k8s-monitoring/README.md.gotmpl, charts/k8s-monitoring/templates/hooks/validate-configuration.yaml, charts/k8s-monitoring/templates/tests/test.yaml, examples/control-plane-metrics/output.yaml, examples/custom-allow-lists/output.yaml, examples/custom-config/output.yaml, examples/default-values/output.yaml, examples/eks-fargate/output.yaml, examples/extra-rules/output.yaml, examples/gke-autopilot/output.yaml, examples/ibm-cloud/output.yaml, examples/logs-only/output.yaml, examples/metrics-only/output.yaml, examples/openshift-compatible/output.yaml, examples/otel-metrics-service/output.yaml, examples/private-image-registry/output.yaml, examples/proxies/output.yaml, examples/scrape-intervals/output.yaml, examples/service-integrations/output.yaml, examples/specific-namespace/output.yaml, examples/traces-enabled/output.yaml, examples/windows-exporter/output.yaml, scripts/setup-local-test-cluster.sh
Need to convert the jobs to pods and stop them from being auto-deleted.
=> Make helm test work with the --logs flag

charts/k8s-monitoring/docs/Troubleshooting.md, charts/k8s-monitoring/values.yaml
also add a note in the troubleshooting doc.
Fixes #309
=> Explicitly add volume mount in the values file

scripts/setup-local-test-cluster.sh
Test cluster script failed for me with the error:
```
Error: INSTALLATION FAILED: repo jetstack not found
```
=> fix: repo jetstack not found

charts/k8s-monitoring/README.md, charts/k8s-monitoring/templates/extra-manifests.yaml, charts/k8s-monitoring/values.yaml
Adds support for extra manifests to deploy objects like ExternalSecrets or SealedSecrets.
=> Support extra k8s manifests

charts/k8s-monitoring/README.md, charts/k8s-monitoring/docs/RBAC.md, charts/k8s-monitoring/values.schema.json, charts/k8s-monitoring/values.yaml
Also regenerate schema and other generated docs
Link to the README: https://github.com/grafana/k8s-monitoring-helm/tree/fix/improve-readme/charts/k8s-monitoring
=> Improve the docs, mostly by turing URLs into links.

.github/configs/cluster-config.yaml, .github/configs/loki.yaml, charts/k8s-monitoring/Chart.yaml, charts/k8s-monitoring/README.md, charts/k8s-monitoring/ci/ci-2-values.yaml, charts/k8s-monitoring/ci/ci-integrations-values.yaml, charts/k8s-monitoring/ci/ci-values.yaml, charts/k8s-monitoring/test/Dockerfile, charts/k8s-monitoring/test/query-test.sh, examples/cluster-with-pvc/output.yaml, examples/control-plane-metrics/output.yaml, examples/custom-config/output.yaml, examples/custom-metrics-tuning/output.yaml, examples/default-values/output.yaml, examples/eks-fargate/output.yaml, examples/extra-rules/output.yaml, examples/gke-autopilot/output.yaml, examples/ibm-cloud/output.yaml, examples/kube-pod-labels/output.yaml, examples/logs-only/output.yaml, examples/metrics-only/output.yaml, examples/openshift-compatible/output.yaml, examples/otel-metrics-service/output.yaml, examples/private-image-registry/output.yaml, examples/proxies/output.yaml, examples/scrape-intervals/output.yaml, examples/service-integrations/output.yaml, examples/specific-namespace/output.yaml, examples/traces-enabled/output.yaml, examples/windows-exporter/output.yaml
Test cluster now has two nodes
Start checking for DPM
Also set the Loki ServiceMonitor to be 1m instead of the default 15s
=> Improve the query test script so it can compare floating point numbers.

charts/k8s-monitoring/Chart.yaml, charts/k8s-monitoring/Makefile, charts/k8s-monitoring/README.md, charts/k8s-monitoring/test/Dockerfile, examples/agent-autoscaling-and-storage/output.yaml, examples/control-plane-metrics/output.yaml, examples/custom-config/output.yaml, examples/custom-metrics-tuning/output.yaml, examples/custom-pricing/output.yaml, examples/default-values/output.yaml, examples/eks-fargate/output.yaml, examples/extra-rules/output.yaml, examples/gke-autopilot/output.yaml, examples/ibm-cloud/output.yaml, examples/kube-pod-labels/output.yaml, examples/logs-only/output.yaml, examples/metrics-only/output.yaml, examples/openshift-compatible/output.yaml, examples/otel-metrics-service/output.yaml, examples/private-image-registry/output.yaml, examples/profiles-enabled/output.yaml, examples/proxies/output.yaml, examples/scrape-intervals/output.yaml, examples/service-integrations/output.yaml, examples/specific-namespace/output.yaml, examples/traces-enabled/output.yaml, examples/windows-exporter/output.yaml
In order to pull an arm64 image from nixery, you need to use the arm64 "metapackage":
https://github.com/tazjin/nixery/issues/13#issuecomment-546372482
=> Build the test image in a way that works for both platform types

CONTRIBUTING.md, Makefile, README.md, scripts/delete-local-test-cluster.sh, scripts/install-deps.sh, scripts/release.sh, scripts/set-version.sh
Also to do: Update the contributor guide to include:
For contributors, how to build, test, make prs
For maintainers, how to merge PRs, and release versions (update version, run the release workflow)
=> Add more helper scripts to make it easier for other contributors and maintainers

.github/workflows/project-assignment.yml
Notice the project assignment. The workflow did that... not me!
=> Create project assignment workflow

charts/k8s-monitoring/templates/alloy_config/_receivers_jaeger.alloy.txt, examples/traces-enabled/metrics.alloy, examples/traces-enabled/output.yaml
Real big change here
Fixes #477
=> chore: fix indentation for jaeger component

examples/alloy-autoscaling-and-storage/README.md, examples/alloy-autoscaling-and-storage/output.yaml, examples/alloy-autoscaling-and-storage/values.yaml
so the logs alloy uses local storage for storing log positions
=> Update storage example

.github/configs/loki.yaml, .github/workflows/helm-test.yml, scripts/setup-local-test-cluster.sh
It also introduces the label `full_test_required` to force the GitHub Action to run the full test, even if [chart-testing](https://github.com/helm/chart-testing) detects that the chart didn't change. In this case, there was no change to the chart, but a test dependency changed, so we want to run the test anyway.
=> Unpin the version and work with Loki 3

charts/k8s-monitoring/docs/Troubleshooting.md
=> Start a general troubleshooting tips section and link to the Alloy UI section

charts/k8s-monitoring/README.md, charts/k8s-monitoring/templates/alloy_config/_profiles_java.alloy.txt, charts/k8s-monitoring/templates/alloy_config/_profiles_pprof.alloy.txt, charts/k8s-monitoring/values.yaml, examples/application-observability/output.yaml, examples/application-observability/profiles.alloy, examples/profiles-enabled/output.yaml, examples/profiles-enabled/profiles.alloy
Fixes #574 
Fixes #587 
Adds a section for Java profiles.
=> Add scraping for Java profiles

charts/k8s-monitoring/README.md, charts/k8s-monitoring/templates/_configs.tpl, charts/k8s-monitoring/templates/alloy_config/_live_debugging.alloy.txt, charts/k8s-monitoring/values.schema.json, charts/k8s-monitoring/values.yaml, examples/custom-config/events.alloy, examples/custom-config/logs.alloy, examples/custom-config/metrics.alloy, examples/custom-config/output.yaml, examples/metric-module-imports-extra-config/metrics.alloy, examples/metric-module-imports-extra-config/output.yaml, examples/service-integrations/logs.alloy, examples/service-integrations/metrics.alloy, examples/service-integrations/output.yaml
also clean up some values.yaml sections
=> Add the ability to set live debugging

charts/k8s-monitoring/Chart.lock, charts/k8s-monitoring/Chart.yaml
=> Don't use two valid paths for conditions

charts/k8s-monitoring/README.md, charts/k8s-monitoring/templates/_config_validations.tpl, charts/k8s-monitoring/templates/_helpers.tpl, charts/k8s-monitoring/templates/alloy-events-config.yaml, charts/k8s-monitoring/templates/alloy-logs-config.yaml, charts/k8s-monitoring/templates/hooks/validate-configuration.yaml, charts/k8s-monitoring/templates/log-service-credentials.yaml, charts/k8s-monitoring/templates/platform_specific/openshift/alloy-scc.yaml, charts/k8s-monitoring/values.yaml
This should detangle it from the existence of pod logs, cluster events, and other pieces
=> Establish the purpose of .Values.logs.enabled

charts/k8s-monitoring/templates/destinations/_destination_loki.tpl, charts/k8s-monitoring/templates/destinations/_destination_otlp.tpl, charts/k8s-monitoring/templates/destinations/_destination_prometheus.tpl, charts/k8s-monitoring/templates/destinations/_destination_pyroscope.tpl
=> Add the ability to use a caFile in tls sections

charts/k8s-monitoring/values.yaml
=> typoCorrection

charts/k8s-monitoring/charts/feature-annotation-autodiscovery/templates/_module.alloy.tpl, charts/k8s-monitoring/charts/feature-annotation-autodiscovery/tests/default_test.yaml, charts/k8s-monitoring/charts/feature-annotation-autodiscovery/tests/namespaced_test.yaml, charts/k8s-monitoring/charts/feature-annotation-autodiscovery/tests/prometheus_annotation_test.yaml, charts/k8s-monitoring/docs/examples/auth/oauth2/alloy-metrics.alloy, charts/k8s-monitoring/docs/examples/auth/oauth2/output.yaml, charts/k8s-monitoring/docs/examples/features/annotation-autodiscovery/default/alloy-metrics.alloy, charts/k8s-monitoring/docs/examples/features/annotation-autodiscovery/default/output.yaml, charts/k8s-monitoring/docs/examples/features/annotation-autodiscovery/prom-annotations/alloy-metrics.alloy, charts/k8s-monitoring/docs/examples/features/annotation-autodiscovery/prom-annotations/output.yaml, charts/k8s-monitoring/docs/examples/metrics-tuning/alloy-metrics.alloy, charts/k8s-monitoring/docs/examples/metrics-tuning/output.yaml, charts/k8s-monitoring/tests/integration/anntoation-autodiscovery/.rendered/output.yaml, charts/k8s-monitoring/tests/integration/anntoation-autodiscovery/deployments/cert-manager.yaml, charts/k8s-monitoring/tests/integration/anntoation-autodiscovery/deployments/grafana.yaml, charts/k8s-monitoring/tests/integration/anntoation-autodiscovery/deployments/nginx-static-metrics.yaml, charts/k8s-monitoring/tests/integration/anntoation-autodiscovery/deployments/prometheus.yaml, charts/k8s-monitoring/tests/integration/anntoation-autodiscovery/deployments/query-test.yaml, charts/k8s-monitoring/tests/integration/anntoation-autodiscovery/values.yaml, charts/k8s-monitoring/tests/integration/control-plane-monitoring/.rendered/output.yaml, charts/k8s-monitoring/tests/integration/control-plane-monitoring/deployments/query-test.yaml, charts/k8s-monitoring/tests/integration/control-plane-monitoring/values.yaml
Also add DPM checks for control plane integration test and add a test for annotation autodiscovery.
=> Fix pod annotation duplication

charts/k8s-monitoring/destinations/prometheus-values.yaml, charts/k8s-monitoring/destinations/pyroscope-values.yaml, charts/k8s-monitoring/docs/destinations/pyroscope.md, charts/k8s-monitoring/schema-mods/definitions/pyroscope-destination.schema.json, charts/k8s-monitoring/templates/destinations/_destination_pyroscope.tpl, charts/k8s-monitoring/values.schema.json
Brings feature parity from v1.
cc @SeamusGrafana
=> Add the ability to specify extra labels for profiles

charts/k8s-monitoring/charts/feature-auto-instrumentation/README.md, charts/k8s-monitoring/charts/feature-auto-instrumentation/schema-mods/remote-beyla-config-data.jq, charts/k8s-monitoring/charts/feature-auto-instrumentation/values.schema.json, charts/k8s-monitoring/charts/feature-auto-instrumentation/values.yaml, charts/k8s-monitoring/docs/examples/features/auto-instrumentation/beyla-metrics-and-traces/README.md, charts/k8s-monitoring/docs/examples/features/auto-instrumentation/beyla-metrics-and-traces/output.yaml, charts/k8s-monitoring/docs/examples/features/auto-instrumentation/beyla-metrics-and-traces/values.yaml, charts/k8s-monitoring/docs/examples/features/auto-instrumentation/beyla-metrics/output.yaml, charts/k8s-monitoring/templates/beyla-config.yaml, charts/k8s-monitoring/tests/beyla_config_test.yaml, charts/k8s-monitoring/tests/integration/auto-instrumentation/.rendered/output.yaml
=> Make it so the beyla config can be config'd

.github/CODEOWNERS, CONTRIBUTING.md, README.md, charts/k8s-monitoring/Chart.yaml, charts/k8s-monitoring/README.md, charts/k8s-monitoring/docs/Migration.md
Also add some details to the contributor guide about the Helm chart's design idioms.
=> Add Robbie as a primary contributor!

README.md
Hard to believe it's 2025 already. 😄
=> Update office hours date in README

charts/k8s-monitoring/README.md, charts/k8s-monitoring/docs/examples/remote-config/README.md, charts/k8s-monitoring/docs/examples/remote-config/alloy-logs.alloy, charts/k8s-monitoring/docs/examples/remote-config/description.txt, charts/k8s-monitoring/docs/examples/remote-config/output.yaml, charts/k8s-monitoring/docs/examples/remote-config/values.yaml, charts/k8s-monitoring/templates/collectors/_collector_remoteConfig.tpl, charts/k8s-monitoring/templates/collectors/_collector_validations.tpl, charts/k8s-monitoring/tests/platform/remote-config/.rendered/output.yaml, charts/k8s-monitoring/tests/platform/remote-config/deployments/query-test.yaml, charts/k8s-monitoring/tests/platform/remote-config/values.yaml, charts/k8s-monitoring/values.schema.json, charts/k8s-monitoring/values.yaml
Enabling remote config now requires setting these environment variables:
* `GCLOUD_FM_COLLECTOR_ID`
* `GCLOUD_RW_API_KEY`
=> Update the remoteconfig platform test to set the expected env vars

charts/k8s-monitoring/charts/feature-integrations/templates/secrets/_helpers.tpl, charts/k8s-monitoring/templates/secrets/_helpers.tpl
=> Remove break and continue, which are only on newer versions of Helm

charts/k8s-monitoring/docs/examples/features/integrations/mimir/README.md, charts/k8s-monitoring/docs/examples/features/integrations/mimir/description.txt
This pull request includes updates to the documentation for the k8s-monitoring integrations, specifically changing references from Grafana Loki to Grafana Mimir.
Documentation updates:
* [`charts/k8s-monitoring/docs/examples/features/integrations/mimir/README.md`](diffhunk://#diff-4b362558934c124884e0b0dfde60993b272efe03f7e042e3096cd15b9bd1597cL5-R7): Updated integration example to demonstrate how to gather metrics and logs from Grafana Mimir instead of Grafana Loki.
* [`charts/k8s-monitoring/docs/examples/features/integrations/mimir/description.txt`](diffhunk://#diff-ad68d8cfc6c1d7c532f4b598bd8a1c159e732b2b60dbd2239e1db4ed2c29a0eaL1-R3): Updated description to reflect the change from Grafana Loki to Grafana Mimir.
=> Mimir readme titles

charts/k8s-monitoring/templates/destinations/_destination_validations.tpl, charts/k8s-monitoring/tests/destination_validations_test.yaml
Also utilize dig that handles undefined fields
=> Add unit tests for the new Grafana cloud validators.

charts/k8s-monitoring/docs/examples/scalability/sharded-kube-state-metrics/README.md, charts/k8s-monitoring/docs/examples/scalability/sharded-kube-state-metrics/description.txt
=> Be explicit that KSM needs to be deleted before upgrading to use sharding

charts/k8s-monitoring/templates/destinations/_destination_validations.tpl
Ensures that it is skipped when using
=> Ensure that the destination URL has been defined before we validate it

charts/k8s-monitoring/charts/feature-integrations/templates/secrets/_helpers.tpl, charts/k8s-monitoring/templates/secrets/_helpers.tpl, charts/k8s-monitoring/templates/secrets/test/secrets.yaml, charts/k8s-monitoring/tests/unittest_secrets_test.yaml
Add unit tests to check functionality before and after
=> Replace the cascading combo if (a & b & c) statement with dig.

charts/k8s-monitoring/charts/feature-prometheus-operator-objects/README.md, charts/k8s-monitoring/charts/feature-prometheus-operator-objects/templates/_notes.tpl, charts/k8s-monitoring/charts/feature-prometheus-operator-objects/templates/_pod_monitors.alloy.tpl, charts/k8s-monitoring/charts/feature-prometheus-operator-objects/templates/_probes.alloy.tpl, charts/k8s-monitoring/charts/feature-prometheus-operator-objects/templates/_service_monitors.alloy.tpl, charts/k8s-monitoring/charts/feature-prometheus-operator-objects/templates/configmap.yaml, charts/k8s-monitoring/charts/feature-prometheus-operator-objects/tests/__snapshot__/default_test.yaml.snap, charts/k8s-monitoring/charts/feature-prometheus-operator-objects/tests/__snapshot__/labels_and_expressions_test.yaml.snap, charts/k8s-monitoring/charts/feature-prometheus-operator-objects/tests/default_test.yaml, charts/k8s-monitoring/charts/feature-prometheus-operator-objects/tests/labels_and_expressions_test.yaml, charts/k8s-monitoring/charts/feature-prometheus-operator-objects/values.schema.json, charts/k8s-monitoring/charts/feature-prometheus-operator-objects/values.yaml, charts/k8s-monitoring/docs/examples/auth/bearer-token/output.yaml, charts/k8s-monitoring/docs/examples/auth/embedded-secrets/output.yaml, charts/k8s-monitoring/docs/examples/auth/external-secrets/output.yaml, charts/k8s-monitoring/docs/examples/auth/oauth2/output.yaml, charts/k8s-monitoring/docs/examples/features/prometheus-operator-objects/default/README.md, charts/k8s-monitoring/docs/examples/features/prometheus-operator-objects/default/alloy-metrics.alloy, charts/k8s-monitoring/docs/examples/features/prometheus-operator-objects/default/values.yaml, charts/k8s-monitoring/tests/integration/prometheus-operator-objects/.rendered/output.yaml, charts/k8s-monitoring/tests/integration/prometheus-operator-objects/deployments/cert-manager.yaml, charts/k8s-monitoring/tests/integration/prometheus-operator-objects/deployments/grafana.yaml, charts/k8s-monitoring/tests/integration/prometheus-operator-objects/deployments/prometheus.yaml, charts/k8s-monitoring/tests/integration/prometheus-operator-objects/deployments/query-test.yaml, charts/k8s-monitoring/tests/integration/prometheus-operator-objects/values.yaml
=> Fix selectors for Prom Operator Objects

charts/k8s-monitoring/charts/feature-integrations/templates/secrets/_helpers.tpl, charts/k8s-monitoring/templates/secrets/_helpers.tpl, charts/k8s-monitoring/templates/secrets/test/secrets.yaml, charts/k8s-monitoring/tests/unittest_secrets_test.yaml
=> Remove more boolean short-circuitting, which doesn't work always

.github/workflows/integration-test.yml, .github/workflows/platform-test.yml, charts/k8s-monitoring/Makefile, charts/k8s-monitoring/tests/platform/eks-addon-with-terraform/.envrc, charts/k8s-monitoring/tests/platform/eks-addon-with-terraform/.gitignore, charts/k8s-monitoring/tests/platform/eks-addon-with-terraform/Makefile, charts/k8s-monitoring/tests/platform/eks-addon-with-terraform/addon.tf, charts/k8s-monitoring/tests/platform/eks-addon-with-terraform/deploy.sh, charts/k8s-monitoring/tests/platform/eks-addon-with-terraform/deployments/query-test.yaml, charts/k8s-monitoring/tests/platform/eks-addon-with-terraform/eks-cluster-config.yaml, charts/k8s-monitoring/tests/platform/eks-addon-with-terraform/provider.tf, charts/k8s-monitoring/tests/platform/eks-addon-with-terraform/values.yaml, charts/k8s-monitoring/tests/platform/eks-addon/.envrc, charts/k8s-monitoring/tests/platform/eks-addon/.gitignore, charts/k8s-monitoring/tests/platform/eks-addon/Makefile, charts/k8s-monitoring/tests/platform/eks-addon/deploy.sh, charts/k8s-monitoring/tests/platform/eks-addon/deployments/query-test.yaml, charts/k8s-monitoring/tests/platform/eks-addon/eks-cluster-config.yaml, charts/k8s-monitoring/tests/platform/eks-addon/values.json, charts/k8s-monitoring/tests/platform/eks-addon/values.yaml
=> Add eks addon tests

charts/k8s-monitoring/docs/examples/features/auto-instrumentation/beyla-metrics-and-traces/README.md, charts/k8s-monitoring/docs/examples/features/auto-instrumentation/beyla-metrics-and-traces/alloy-metrics.alloy, charts/k8s-monitoring/docs/examples/features/auto-instrumentation/beyla-metrics-and-traces/alloy-receiver.alloy, charts/k8s-monitoring/docs/examples/features/auto-instrumentation/beyla-metrics-and-traces/output.yaml, charts/k8s-monitoring/docs/examples/features/auto-instrumentation/beyla-metrics-and-traces/values.yaml, charts/k8s-monitoring/docs/examples/features/auto-instrumentation/beyla-metrics/README.md, charts/k8s-monitoring/docs/examples/features/auto-instrumentation/beyla-metrics/values.yaml, charts/k8s-monitoring/docs/examples/features/auto-instrumentation/discovery-rules/README.md, charts/k8s-monitoring/docs/examples/features/auto-instrumentation/discovery-rules/alloy-metrics.alloy, charts/k8s-monitoring/docs/examples/features/auto-instrumentation/discovery-rules/description.txt, charts/k8s-monitoring/docs/examples/features/auto-instrumentation/discovery-rules/output.yaml, charts/k8s-monitoring/docs/examples/features/auto-instrumentation/discovery-rules/values.yaml
Fixing the cluster name on two examples
Adding a new example that passes discovery rules to beyla
=> Update Beyla examples

charts/k8s-monitoring/docs/examples/remote-config/README.md, charts/k8s-monitoring/docs/examples/remote-config/alloy-logs.alloy, charts/k8s-monitoring/docs/examples/remote-config/alloy-metrics.alloy, charts/k8s-monitoring/docs/examples/remote-config/output.yaml, charts/k8s-monitoring/docs/examples/remote-config/values.yaml, charts/k8s-monitoring/schema-mods/types-and-enums.json, charts/k8s-monitoring/templates/secrets/test/secrets.yaml, charts/k8s-monitoring/tests/unittest_secrets_test.yaml, charts/k8s-monitoring/values.schema.json
Don't define the secret in the env var
=> Update the fleet management example to use the password in the secret

charts/k8s-monitoring/templates/_platform_validations.tpl, charts/k8s-monitoring/templates/_validations.tpl, charts/k8s-monitoring/templates/validations.yaml, charts/k8s-monitoring/tests/annotation_autodiscovery_test.yaml, charts/k8s-monitoring/tests/cluster_events_test.yaml, charts/k8s-monitoring/tests/destination_validations_test.yaml, charts/k8s-monitoring/tests/platform_validations_test.yaml, charts/k8s-monitoring/tests/validations_test.yaml
Also add EKS Fargate platform test
=> Add AKS cluster validation

charts/k8s-monitoring/charts/feature-integrations/templates/_integration_mysql_metrics.tpl, charts/k8s-monitoring/charts/feature-integrations/templates/configmap.yaml, charts/k8s-monitoring/charts/feature-integrations/tests/__snapshot__/mysql_metrics_test.yaml.snap, charts/k8s-monitoring/charts/feature-integrations/tests/mysql_metrics_test.yaml, charts/k8s-monitoring/docs/examples/features/integrations/mysql/alloy-metrics.alloy, charts/k8s-monitoring/docs/examples/features/integrations/mysql/output.yaml, charts/k8s-monitoring/tests/integration/service-integrations/mysql/.rendered/output.yaml, charts/k8s-monitoring/tests/integration/service-integrations/mysql/deployments/mysql.yaml, charts/k8s-monitoring/tests/integration/service-integrations/mysql/values.yaml
This better matches most environments.
=> Switch to use all secrets, rather than the usernameFrom

charts/k8s-monitoring/charts/feature-prometheus-operator-objects/templates/_probes.alloy.tpl, charts/k8s-monitoring/charts/feature-prometheus-operator-objects/tests/__snapshot__/default_test.yaml.snap, charts/k8s-monitoring/charts/feature-prometheus-operator-objects/tests/__snapshot__/labels_and_expressions_test.yaml.snap, charts/k8s-monitoring/docs/examples/auth/bearer-token/alloy-metrics.alloy, charts/k8s-monitoring/docs/examples/auth/bearer-token/output.yaml, charts/k8s-monitoring/docs/examples/auth/embedded-secrets/alloy-metrics.alloy, charts/k8s-monitoring/docs/examples/auth/embedded-secrets/output.yaml, charts/k8s-monitoring/docs/examples/auth/external-secrets/alloy-metrics.alloy, charts/k8s-monitoring/docs/examples/auth/external-secrets/output.yaml, charts/k8s-monitoring/docs/examples/auth/oauth2/alloy-metrics.alloy, charts/k8s-monitoring/docs/examples/auth/oauth2/output.yaml, charts/k8s-monitoring/docs/examples/exclude-by-namespace/alloy-metrics.alloy, charts/k8s-monitoring/docs/examples/exclude-by-namespace/output.yaml, charts/k8s-monitoring/docs/examples/features/prometheus-operator-objects/default/alloy-metrics.alloy, charts/k8s-monitoring/docs/examples/features/prometheus-operator-objects/default/output.yaml, charts/k8s-monitoring/docs/examples/include-by-namespace/alloy-metrics.alloy, charts/k8s-monitoring/docs/examples/include-by-namespace/output.yaml, charts/k8s-monitoring/tests/integration/prometheus-operator-objects/.rendered/output.yaml
Small typo fix. Should I update the corresponding test snapshots ?
=> Fix label of prometheus.operator.probes component

charts/k8s-monitoring/destinations/loki-values.yaml, charts/k8s-monitoring/destinations/prometheus-values.yaml, charts/k8s-monitoring/destinations/pyroscope-values.yaml, charts/k8s-monitoring/docs/destinations/loki.md, charts/k8s-monitoring/docs/destinations/prometheus.md, charts/k8s-monitoring/docs/destinations/pyroscope.md, charts/k8s-monitoring/docs/examples/proxies/alloy-profiles.alloy, charts/k8s-monitoring/docs/examples/proxies/output.yaml, charts/k8s-monitoring/schema-mods/definitions/loki-destination.schema.json, charts/k8s-monitoring/schema-mods/definitions/prometheus-destination.schema.json, charts/k8s-monitoring/schema-mods/definitions/pyroscope-destination.schema.json, charts/k8s-monitoring/templates/destinations/_destination_loki.tpl, charts/k8s-monitoring/templates/destinations/_destination_prometheus.tpl, charts/k8s-monitoring/templates/destinations/_destination_pyroscope.tpl, charts/k8s-monitoring/values.schema.json
Add proxyFromEnvironment support for prometheus, loki, and pyroscope destinations
=> Fix Pyroscope proxies

.configs/prometheus.yaml, .github/configs/prometheus.yaml, charts/k8s-monitoring/tests/integration/alternative-deployments/argocd/deployments/prometheus.yaml, charts/k8s-monitoring/tests/integration/alternative-deployments/terraform/deployments/prometheus.yaml, charts/k8s-monitoring/tests/integration/annotation-autodiscovery/deployments/prometheus.yaml, charts/k8s-monitoring/tests/integration/auto-instrumentation/deployments/prometheus.yaml, charts/k8s-monitoring/tests/integration/cluster-monitoring/deployments/prometheus.yaml, charts/k8s-monitoring/tests/integration/control-plane-monitoring/deployments/prometheus.yaml, charts/k8s-monitoring/tests/integration/istio-service-mesh/deployments/prometheus.yaml, charts/k8s-monitoring/tests/integration/pod-logs/log-metrics/deployments/prometheus.yaml, charts/k8s-monitoring/tests/integration/prometheus-io-annotations/deployments/prometheus.yaml, charts/k8s-monitoring/tests/integration/prometheus-operator-objects/deployments/prometheus.yaml, charts/k8s-monitoring/tests/integration/service-integrations/alloy/deployments/prometheus.yaml, charts/k8s-monitoring/tests/integration/service-integrations/cert-manager/deployments/prometheus.yaml, charts/k8s-monitoring/tests/integration/service-integrations/coredns/deployments/prometheus.yaml, charts/k8s-monitoring/tests/integration/service-integrations/grafana/deployments/prometheus.yaml, charts/k8s-monitoring/tests/integration/service-integrations/loki/deployments/prometheus.yaml, charts/k8s-monitoring/tests/integration/service-integrations/mysql/deployments/prometheus.yaml, charts/k8s-monitoring/tests/integration/service-integrations/tempo/deployments/prometheus.yaml, charts/k8s-monitoring/tests/integration/sharded-kube-state-metrics/deployments/prometheus.yaml, charts/k8s-monitoring/tests/integration/split-destinations/deployments/prometheus.yaml, charts/k8s-monitoring/tests/integration/statsd/deployments/prometheus.yaml
Needed to change how we enable remote-write receivers
=> Remove pinned prometheus version

charts/k8s-monitoring-v1/README.md, charts/k8s-monitoring-v1/values.yaml
Batch is in "elements", not bytes.
=> Fix the batch comment

charts/k8s-monitoring/tests/integration/application-observability/deployments/alloy-instrumented.yaml, charts/k8s-monitoring/tests/integration/application-observability/deployments/grafana.yaml, charts/k8s-monitoring/tests/integration/application-observability/deployments/prometheus.yaml, charts/k8s-monitoring/tests/integration/application-observability/deployments/query-test.yaml, charts/k8s-monitoring/tests/integration/application-observability/deployments/tempo.yaml, charts/k8s-monitoring/tests/integration/application-observability/values.yaml
Exercises and tests the host info connector
=> Add an integration test for Application Observability

charts/k8s-monitoring/templates/_platform_validations.tpl
Instead, try to shortcut a little bit with a platform value.
=> Remove break statement, which doesn't have very good broad support.

charts/k8s-monitoring/charts/feature-pod-logs/templates/_collector_validation.tpl, charts/k8s-monitoring/charts/feature-pod-logs/templates/test/collector.yaml, charts/k8s-monitoring/charts/feature-pod-logs/tests/collector_validation_test.yaml
Also add unit tests for ensuring they work properly
=> Fix pod log collector validation

charts/k8s-monitoring/Makefile, charts/k8s-monitoring/docs/Images.md
=> Add an images doc that shows the list of images that could be used

charts/k8s-monitoring/destinations/otlp-values.yaml, charts/k8s-monitoring/docs/destinations/otlp.md, charts/k8s-monitoring/docs/examples/proxies/README.md, charts/k8s-monitoring/docs/examples/proxies/alloy-logs.alloy, charts/k8s-monitoring/docs/examples/proxies/alloy-profiles.alloy, charts/k8s-monitoring/docs/examples/proxies/alloy-receiver.alloy, charts/k8s-monitoring/docs/examples/proxies/alloy-singleton.alloy, charts/k8s-monitoring/docs/examples/proxies/description.txt, charts/k8s-monitoring/docs/examples/proxies/output.yaml, charts/k8s-monitoring/docs/examples/proxies/values.yaml, charts/k8s-monitoring/schema-mods/definitions/otlp-destination.schema.json, charts/k8s-monitoring/templates/destinations/_destination_validations.tpl, charts/k8s-monitoring/tests/destination_validations_test.yaml, charts/k8s-monitoring/values.schema.json
=> Add the ability to set proxyURL for otlp http destinations

charts/k8s-monitoring/charts/feature-node-logs/templates/_collector_validation.tpl, charts/k8s-monitoring/charts/feature-node-logs/templates/test/collector.yaml, charts/k8s-monitoring/charts/feature-node-logs/tests/collector_validation_test.yaml, charts/k8s-monitoring/charts/feature-pod-logs/templates/_collector_validation.tpl, charts/k8s-monitoring/charts/feature-pod-logs/tests/collector_validation_test.yaml
It's not actually a functional check and has time when it's important
=> Remove validation for clustering with volumes.

charts/k8s-monitoring/charts/feature-application-observability/templates/_processor_resourcedetection.tpl
Fixes https://github.com/grafana/k8s-monitoring-helm/issues/1557
=> Fix invalid kubernetesNode resource detector

.github/workflows/helm-release-v1.yml, .github/workflows/integration-test.yml, .github/workflows/platform-test.yml, .github/workflows/release.yml, .github/workflows/test-v1.yml, charts/k8s-monitoring/docs/examples/private-image-registries/globally/README.md, charts/k8s-monitoring/docs/examples/private-image-registries/globally/alloy-receiver.alloy, charts/k8s-monitoring/docs/examples/private-image-registries/globally/output.yaml, charts/k8s-monitoring/docs/examples/private-image-registries/globally/values.yaml, charts/k8s-monitoring/docs/examples/private-image-registries/individual/README.md, charts/k8s-monitoring/docs/examples/private-image-registries/individual/alloy-receiver.alloy, charts/k8s-monitoring/docs/examples/private-image-registries/individual/output.yaml, charts/k8s-monitoring/docs/examples/private-image-registries/individual/values.yaml, charts/k8s-monitoring/templates/alloy-sampler.yaml, charts/k8s-monitoring/templates/collectors/_collector_helpers.tpl
Also add sampler to the image registry examples
Finally, pin helm in github actions to 3.17.3
=> Pass globals handled by Alloy down from our values to the alloy instance

charts/k8s-monitoring/destinations/otlp-values.yaml, charts/k8s-monitoring/docs/destinations/otlp.md, charts/k8s-monitoring/schema-mods/definitions/otlp-destination.schema.json, charts/k8s-monitoring/templates/alloy-sampler.yaml, charts/k8s-monitoring/templates/sampler/_receiver_otlp.tpl, charts/k8s-monitoring/tests/integration/tail-sampling/.rendered/output.yaml, charts/k8s-monitoring/tests/integration/tail-sampling/values.yaml, charts/k8s-monitoring/values.schema.json
=> add max received message size config for sampler receiver

charts/k8s-monitoring-v1/README.md, charts/k8s-monitoring-v1/values.yaml, charts/k8s-monitoring/charts/feature-profiling/README.md, charts/k8s-monitoring/charts/feature-profiling/values.yaml
Description is misleading, this is more accurate.
=> Update java.enabled description

charts/k8s-monitoring/templates/alloy-servicegraph.yaml, charts/k8s-monitoring/tests/__snapshot__/servicegraph_test.yaml.snap, charts/k8s-monitoring/tests/servicegraph_test.yaml
=> update secret handling for servicegraph metric destinations

charts/k8s-monitoring/docs/examples/service-integrations/mongodb-atlas/README.md, charts/k8s-monitoring/docs/examples/service-integrations/mongodb-atlas/alloy-metrics.alloy, charts/k8s-monitoring/docs/examples/service-integrations/mongodb-atlas/output.yaml, charts/k8s-monitoring/docs/examples/service-integrations/mongodb-atlas/values.yaml
Fixing the mongodb Atlas URL decoding issue
=> fix(mongodb-atlas): Fixing Mongodb Atlas Integration

charts/k8s-monitoring/destinations/otlp-values.yaml, charts/k8s-monitoring/docs/destinations/otlp.md, charts/k8s-monitoring/docs/examples/auth/sigv4/README.md, charts/k8s-monitoring/docs/examples/auth/sigv4/values.yaml, charts/k8s-monitoring/schema-mods/definitions/otlp-destination.schema.json, charts/k8s-monitoring/schema-mods/types-and-enums.json, charts/k8s-monitoring/templates/destinations/_destination_otlp.tpl, charts/k8s-monitoring/values.schema.json
=> Add Sigv4 authentication for otlp destinations

charts/k8s-monitoring/docs/examples/platforms/gke-autopilot/README.md, charts/k8s-monitoring/docs/examples/platforms/gke-autopilot/alloy-metrics.alloy, charts/k8s-monitoring/docs/examples/platforms/gke-autopilot/output.yaml, charts/k8s-monitoring/docs/examples/platforms/gke-autopilot/values.yaml
disable windows-exporter and remove dockercontainers
=> Update the GKE autopilot example

charts/k8s-monitoring/charts/feature-application-observability/templates/_connector_span_metrics.tpl, charts/k8s-monitoring/tests/integration/application-observability/.rendered/output.yaml, charts/k8s-monitoring/tests/integration/application-observability/test-plan.yaml, charts/k8s-monitoring/tests/integration/application-observability/values.yaml
=> include `collector.id` in span metrics transform

charts/k8s-monitoring-v1/README.md, charts/k8s-monitoring-v1/docs/examples/application-observability/profiles.alloy, charts/k8s-monitoring-v1/docs/examples/custom-config/profiles.alloy, charts/k8s-monitoring-v1/docs/examples/profiles-enabled/profiles.alloy, charts/k8s-monitoring-v1/templates/_helpers.tpl, charts/k8s-monitoring-v1/templates/alloy_config/_profiles_ebpf.alloy.txt, charts/k8s-monitoring-v1/templates/alloy_config/_profiles_java.alloy.txt, charts/k8s-monitoring-v1/templates/alloy_config/_profiles_pprof.alloy.txt, charts/k8s-monitoring-v1/tests/integration/test-1/.rendered/output.yaml, charts/k8s-monitoring-v1/values.schema.json, charts/k8s-monitoring-v1/values.yaml
Should not change the behavior, because it's still opt-out, but can use annotations to disable scrape.
=> Add annotation control for profiles to v1.

charts/k8s-monitoring/docs/examples/platforms/azure-aks/README.md, charts/k8s-monitoring/docs/examples/platforms/azure-aks/values.yaml, charts/k8s-monitoring/templates/_platform_validations.tpl, charts/k8s-monitoring/tests/platform/aks/values.yaml, charts/k8s-monitoring/tests/platform_validations_aks_test.yaml, charts/k8s-monitoring/tests/platform_validations_openshift_test.yaml
=> Fix the platform validation so it works with collectorCommon

charts/k8s-monitoring/templates/features/_feature_cluster_metrics.tpl
=> Fix OpenCost validation when using destinationsMap

charts/k8s-monitoring/charts/feature-pod-logs/templates/_common_pod_discovery.alloy.tpl
Small change, I think this comment is out of date.
=> Update comment by removing k8s.pod.name from discovery rule

charts/k8s-monitoring/charts/feature-application-observability/README.md, charts/k8s-monitoring/charts/feature-application-observability/values.yaml, charts/k8s-monitoring/tests/integration/application-observability/.rendered/output.yaml
=> update span metrics default histogram unit to seconds
