- tests/Makefile
It now properly extracts the river file and uses Grafana Agent fmt to check the syntax.
> Fix make lint-config 

- charts/k8s-monitoring/Chart.yaml
- charts/k8s-monitoring/README.md
- charts/k8s-monitoring/values.yaml
Fixes #48
The `CLUSTER_ID` environment variable on the Opencost pod is set to a default value of `default-cluster` in the Opencost helm chart, so we provide a value to override this.
> Value for opencost CLUSTER_ID

- .gitattributes
- charts/k8s-monitoring/Chart.yaml
- charts/k8s-monitoring/README.md
- charts/k8s-monitoring/templates/agent_config/_loki.river.txt
- charts/k8s-monitoring/templates/agent_config/_prometheus.river.txt
- charts/k8s-monitoring/values.yaml
- examples/custom-config/logs.river
- examples/custom-config/metrics.river
- examples/custom-config/output.yaml
- examples/custom-config/values.yaml
This pull request introduces the feature to include custom external labels (e.g. region, cloud, ) to all time series and/or logs forwarded to external systems such as Grafana Cloud.  
Presently only the `cluster` label is specified which is not sufficient when working with multiple clusters and agents.
> feat: Custom External Labels for Prometheus metrics and Loki logs

- charts/k8s-monitoring/Chart.yaml
- charts/k8s-monitoring/README.md
- charts/k8s-monitoring/templates/agent_config/_loki.river.txt
- charts/k8s-monitoring/templates/agent_config/_prometheus.river.txt
- charts/k8s-monitoring/templates/credentials.yaml
- charts/k8s-monitoring/values.yaml
- examples/logs-only/logs.river
- examples/logs-only/output.yaml
- examples/logs-only/values.yaml
- examples/metrics-only/metrics.river
- examples/metrics-only/output.yaml
- examples/metrics-only/values.yaml
This MR adds the ability to push tenant IDs with the Loki & Prometheus configs in the format Mimir and Loki allow for.
This is to make the system usable by people like us who run Mimir & Loki OSS on-prem, and need to set the tenant IDs in the Grafana Agent config.
> feat: include 'tenantId' field in values for on-prem mimir & loki auth

- charts/k8s-monitoring/Chart.yaml
- charts/k8s-monitoring/README.md
- charts/k8s-monitoring/templates/agent_config/_loki.river.txt
- charts/k8s-monitoring/templates/agent_config/_prometheus.river.txt
- examples/logs-only/logs.river
- examples/logs-only/output.yaml
- examples/metrics-only/metrics.river
- examples/metrics-only/output.yaml
Tenant IDs cannot be secrets, because that conflicts with the agent flow type system which expects them to be strings
> Fix: Treat TenantIDs as strings, not secrets

- charts/k8s-monitoring/Chart.yaml
- charts/k8s-monitoring/README.md
- charts/k8s-monitoring/templates/agent_config/_agent.river.txt
- charts/k8s-monitoring/templates/agent_config/_cadvisor.river.txt
- charts/k8s-monitoring/templates/agent_config/_kube_state_metrics.river.txt
- charts/k8s-monitoring/templates/agent_config/_kubelet.river.txt
- charts/k8s-monitoring/templates/agent_config/_node_exporter.river.txt
- charts/k8s-monitoring/templates/agent_config/_opencost.txt
- charts/k8s-monitoring/templates/agent_config/_pod_monitors.txt
- charts/k8s-monitoring/templates/agent_config/_service_monitors.txt
- charts/k8s-monitoring/templates/agent_config/_windows_exporter.river.txt
- examples/custom-allow-lists/metrics.river
- examples/custom-allow-lists/output.yaml
- examples/custom-config/metrics.river
- examples/custom-config/output.yaml
- examples/default-values/metrics.river
- examples/default-values/output.yaml
- examples/extra-rules/metrics.river
- examples/extra-rules/output.yaml
- examples/metrics-only/metrics.river
- examples/metrics-only/output.yaml
- examples/openshift-compatible/metrics.river
- examples/openshift-compatible/output.yaml
- examples/windows-exporter/metrics.river
- examples/windows-exporter/output.yaml
While the Agent StatefulSet was told to enable clustering, none of the `prometheus.scrape` components enabled it. This fixes it.
Note to reviewers: To see the generated config, expand any of the `metrics.river` files. This only affects the grafana agent StatefulSet that processes metrics, not the Daemonset that processes logs.
> Enable clustering in the scrape components

- .github/configs/grafana.yaml
- .github/configs/loki.yaml
- .github/configs/mimir.yaml
- .github/workflows/helm-release.yml
- .github/workflows/helm-test.yml
- Makefile
- charts/k8s-monitoring/.helmignore
- charts/k8s-monitoring/ci/ci-values.yaml
This PR does the following:
* Stop auto-releasing on merges to main (fixes #68)
* On PRs and merges to main, use GitHub action to deploy the helm chart and test that the pods come online.
* Create a cluster with Kind
* Deploy Mimir
* Deploy Loki
* Deploy Grafana (not really needed, but useful for connecting the above and when testing locally)
* Deploy the Kubernetes Monitoring Helm chart
> Enable CI testing for PRs

- .github/configs/updatecli.d/grafana-agent.yaml
- .github/configs/updatecli.d/kube-state-metrics.yaml
- .github/configs/updatecli.d/node-exporter.yaml
- .github/configs/updatecli.d/opencost.yaml
- .github/configs/updatecli.d/prometheus-operator-crds.yaml
- .github/configs/updatecli.d/windows-exporter.yaml
- .github/workflows/check-for-dependency-updates.yaml
Fixes #106 
This action generated the `[dependency] ...` Pull Requests that are open right now.
Note for reviewers:
* Updatecli (if you're not familiar) knows how to check helm chart repositories for updates and will locally modify our helm chart source with the updated version. It seems to have the ability to create PRs, but we need to run `helm-docs` and regenerate the examples before making the PR.  Also, their docs on PR creation are outdated and I couldn't get it to work reliably.
* Each .github/configs/updatecli.d/* and their associated section in the workflow are nearly identical. Review for clarity of a single flow, then check for copy-paste errors.
> Add github action to update dependencies

- charts/k8s-monitoring/Chart.yaml
- charts/k8s-monitoring/README.md
Add source, to point to the charts source code. 
Very helpful if the chart is displayed based on chart.yaml file and there is no reference where the code is.
In Particular in artifact hub. it is helpful, to know where the templates are.
> Update Chart.yaml add sourse

- charts/k8s-monitoring/templates/_helpers.tpl
- charts/k8s-monitoring/templates/grafana-agent-config.yaml
- charts/k8s-monitoring/templates/grafana-agent-logs-config.yaml
Tested with Helm 3.5:
```
% docker run -it --rm -v $(pwd):/src alpine/helm:3.5.4 template k8smon /src/charts/k8s-monitoring -f /src/examples/default-values/values.yaml
Error: template: k8s-monitoring/templates/grafana-agent-logs-config.yaml:1:4: executing "k8s-monitoring/templates/grafana-agent-logs-config.yaml" at <include "checkHelmVersion" .>: error calling include: template: k8s-monitoring/templates/_helpers.tpl:6:3: executing "checkHelmVersion" at <fail "Helm version 3.7 or later is required for this chart">: error calling fail: Helm version 3.7 or later is required for this chart
Use --debug flag to render out invalid YAML
```
Tested with Helm 3.6:
```
% docker run -it --rm -v $(pwd):/src alpine/helm:3.6.3 template k8smon /src/charts/k8s-monitoring -f …
```
> Add a check for Helm version. It'll give a better error message on Helm CLIs earlier than 3.7

- charts/k8s-monitoring/README.md
- charts/k8s-monitoring/templates/_helpers.tpl
- charts/k8s-monitoring/templates/agent_config/_kubernetes_monitoring_telemetry.river.txt
- charts/k8s-monitoring/templates/kubernetes-monitoring-telemetry.yaml
- charts/k8s-monitoring/values.yaml
- examples/custom-allow-lists/metrics.river
- examples/custom-allow-lists/output.yaml
- examples/custom-config/metrics.river
- examples/custom-config/output.yaml
- examples/default-values/metrics.river
- examples/default-values/output.yaml
- examples/extra-rules/metrics.river
- examples/extra-rules/output.yaml
- examples/logs-only/output.yaml
- examples/metrics-only/metrics.river
- examples/metrics-only/output.yaml
- examples/openshift-compatible/metrics.river
- examples/openshift-compatible/output.yaml
- examples/scrape-intervals/metrics.river
- examples/scrape-intervals/output.yaml
- examples/specific-namespace/metrics.river
- examples/specific-namespace/output.yaml
- examples/traces-enabled/metrics.river
- examples/traces-enabled/output.yaml
- examples/windows-exporter/metrics.river
- examples/windows-exporter/output.yaml
This creates a config map with a static metric defined: `grafana_kubernetes_monitoring_build_info`.
That metric has five labels:
* `version` - the chart version
* `metrics` - If metrics are enabled, will list the metric sources that are also enabled: "agent", "kube-state-metrics", "node-exporter", "windows-exporter", "kubelet", "cadvisor", "cost"
* `logs` - If logs are enabled, will list "events" and/or "pod_logs"
* `traces` - "enabled" or "disabled" based on the state of `.Values.traces.enabled`
* `deployments` - The list of subcharts that are being deployed
The configmap is mounted to the agent pod, then scraped using `prometheus.exporter.unix`'s textfile scraper.
Fixes #143
> Add static telemetry metric with informaiton about chart version and enabled features

- charts/k8s-monitoring/templates/_helpers.tpl
- charts/k8s-monitoring/templates/grafana-agent-config.yaml
- charts/k8s-monitoring/templates/grafana-agent-logs-config.yaml
The idea was to check that we're running a version of Helm after 3.7, but the .Capabilities.HelmVersion wasn't added until 3.9. Meaning this check will either:
* Always pass on versions 3.9 or later
* Will fail on versions 3.8 or earlier
> Remove version check

- charts/k8s-monitoring/templates/crds/check-for-crds.yaml
```
% helm ls -A                      
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                           APP VERSION
promcrds        default         1               2023-10-04 08:50:25.602548 -0500 CDT    deployed        prometheus-operator-crds-6.0.0  v0.68.0    
% helm install k8smon -n monitoring --create-namespace ~/src/grafana/k8s-monitoring-helm/charts/k8s-monitoring -f local-values.yaml
Error: INSTALLATION FAILED: execution error at (k8s-monitoring/templates/crds/check-for-crds.yaml:2:5): This chart is attempting to deploy the Prometheus Operator CRDs, but they have already been installed on this cluster.
Please set: 
prometheus-operator-crds:
enabled: false
and re-deploy
% echo "prometheus-operator-crds:" >> …
```
> Add check for the Prometheus Operator CRDs and print a friendly error message if they're already present

- charts/k8s-monitoring/values.yaml
- examples/default-values/output.yaml
- examples/extra-rules/output.yaml
- examples/gke-autopilot/README.md
- examples/gke-autopilot/logs.river
- examples/gke-autopilot/metrics.river
- examples/gke-autopilot/output.yaml
- examples/gke-autopilot/values.yaml
- examples/logs-only/output.yaml
- examples/openshift-compatible/output.yaml
- examples/private-image-registry/output.yaml
- examples/specific-namespace/output.yaml
- examples/traces-enabled/output.yaml
- examples/windows-exporter/output.yaml
Also stop mounting `/var/lib/docker/containers`, which is not allowed on autopilot cluster. I don't think it is necessary anymore anyway.
> Add GKE Autopilot example, which just skips Node Exporter.

- charts/k8s-monitoring/README.md
- charts/k8s-monitoring/README.md.gotmpl
While deploying to my cluster I noticed that the example values.yaml in the readme is not correct. 
The `username` and `password` values should be under the key `basicAuth` for both loki and prometheus.
> fix readme

- charts/k8s-monitoring/README.md
- charts/k8s-monitoring/templates/agent_config/_traces.river.txt
- charts/k8s-monitoring/values.schema.json
- charts/k8s-monitoring/values.yaml
- examples/traces-enabled/metrics.river
- examples/traces-enabled/output.yaml
Exposes this parameter: https://grafana.com/docs/agent/latest/flow/reference/components/otelcol.processor.batch/
> Add the ability to set the max batch size for traces

- charts/k8s-monitoring/templates/hooks/_helpers.tpl
- charts/k8s-monitoring/templates/hooks/grafana-agent-config-test.yaml
- charts/k8s-monitoring/templates/hooks/validate-configuration.yaml
- charts/k8s-monitoring/templates/tests/_helpers.tpl
- charts/k8s-monitoring/templates/tests/test.yaml
- examples/control-plane-metrics/output.yaml
- examples/custom-allow-lists/output.yaml
- examples/custom-config/output.yaml
- examples/default-values/output.yaml
- examples/extra-rules/output.yaml
- examples/gke-autopilot/output.yaml
- examples/logs-only/output.yaml
- examples/metrics-only/output.yaml
- examples/openshift-compatible/output.yaml
- examples/private-image-registry/output.yaml
- examples/scrape-intervals/output.yaml
- examples/specific-namespace/output.yaml
- examples/traces-enabled/output.yaml
- examples/windows-exporter/output.yaml
- tests/spec/trace-port-check_spec.sh
Also, consolidate the config test into a single job
This should eliminate issues with conflicting configmaps.
Fixes #207
> Rename the config validator and the helm test hooks.

- charts/k8s-monitoring/templates/_helpers.tpl
- charts/k8s-monitoring/templates/agent_config/_pod_logs.river.txt
- examples/control-plane-metrics/logs.river
- examples/control-plane-metrics/output.yaml
- examples/custom-config/logs.river
- examples/custom-config/output.yaml
- examples/default-values/logs.river
- examples/default-values/output.yaml
- examples/extra-rules/logs.river
- examples/extra-rules/output.yaml
- examples/gke-autopilot/logs.river
- examples/gke-autopilot/output.yaml
- examples/logs-only/logs.river
- examples/logs-only/output.yaml
- examples/openshift-compatible/logs.river
- examples/openshift-compatible/output.yaml
- examples/private-image-registry/logs.river
- examples/private-image-registry/output.yaml
- examples/specific-namespace/logs.river
- examples/specific-namespace/output.yaml
- examples/traces-enabled/logs.river
- examples/traces-enabled/output.yaml
- examples/windows-exporter/logs.river
- examples/windows-exporter/output.yaml
Limit the amount of pods discovered by filtering to only the pods on the same node as the agent. This reduces the amount of pods that need to be filtered out later on.
> For pod logs, filter to the pods only on the same node

- charts/k8s-monitoring/README.md
- charts/k8s-monitoring/ci/ci-values.yaml
- charts/k8s-monitoring/scripts/query-test.sh
- charts/k8s-monitoring/templates/tests/test.yaml
- charts/k8s-monitoring/values.yaml
- examples/control-plane-metrics/output.yaml
- examples/custom-allow-lists/output.yaml
- examples/custom-config/output.yaml
- examples/default-values/output.yaml
- examples/eks-fargate/output.yaml
- examples/extra-rules/output.yaml
- examples/gke-autopilot/output.yaml
- examples/logs-only/output.yaml
- examples/metrics-only/output.yaml
- examples/openshift-compatible/output.yaml
- examples/otel-metrics-service/output.yaml
- examples/private-image-registry/output.yaml
- examples/scrape-intervals/output.yaml
- examples/specific-namespace/output.yaml
- examples/traces-enabled/output.yaml
- examples/windows-exporter/output.yaml
This PR extracts the script that does the testing into its own file. That let's people run it on the CLI if they want.
It also adds a `type` field that lets the tests run PromQL or LogQL tests.
I'm not adding the LogQL queries for cluster events or pod logs to the default set of queries, though, because that requires the access token to be able to read logs from loki. By default, our access token only has write permissions to grafana cloud loki.
> Improve the Helm test job so it can run LogQL queries

- charts/k8s-monitoring/templates/agent_config/_traces.river.txt
See [internal slack discussion](https://raintank-corp.slack.com/archives/CSN5HV0CQ/p1700825749658259?thread_ts=1700746376.176619&cid=CSN5HV0CQ), Agent team is looking at disabling debug metrics by default, which is the opposite of the current default.
This means a slight change in logic required for the recent change introduced in #262, to be explict about the value instead of relying on the default.
> fix: Prepare for agent inverting default debug_metrics value

- .github/workflows/helm-test.yml
`git describe --abbrev=0 --tags` gets the latest release (as a git tag).
`ct list-changes` takes a `--since` which uses a git tag.
> When determining when to run the tests, check against the latest release, not against main

- charts/k8s-monitoring/README.md
- charts/k8s-monitoring/values.schema.json
- charts/k8s-monitoring/values.yaml
Because the values file entry was empty, the schema was generated to use "null" not "string".
> Fix schema for annotations extra rules

- charts/k8s-monitoring/Chart.yaml
- charts/k8s-monitoring/README.md
- charts/k8s-monitoring/ci/ci-2-values.yaml
- charts/k8s-monitoring/ci/ci-integrations-values.yaml
- charts/k8s-monitoring/ci/ci-values.yaml
- charts/k8s-monitoring/templates/tests/test.yaml
- charts/k8s-monitoring/test/query-test.sh
- examples/cluster-with-pvc/output.yaml
- examples/control-plane-metrics/output.yaml
- examples/custom-config/output.yaml
- examples/custom-metrics-tuning/output.yaml
- examples/default-values/output.yaml
- examples/eks-fargate/output.yaml
- examples/extra-rules/output.yaml
- examples/gke-autopilot/output.yaml
- examples/ibm-cloud/output.yaml
- examples/logs-only/output.yaml
- examples/metrics-only/output.yaml
- examples/openshift-compatible/output.yaml
- examples/otel-metrics-service/output.yaml
- examples/private-image-registry/output.yaml
- examples/proxies/output.yaml
- examples/scrape-intervals/output.yaml
- examples/service-integrations/output.yaml
- examples/specific-namespace/output.yaml
- examples/traces-enabled/output.yaml
- examples/windows-exporter/output.yaml
This change adds the ability to support an `expect` section in the test queries.
For example:
```
- query: "count(kube_pod_info{cluster=\"ci-test-cluster-2\", color=\"blue\"})"
type: promql
expect:
operator: ">"
value: 1
```
Will not only check that the query returns successfully, but will assert that the value is greater than 1.
Also supported are counting the number of results, such as:
```
metrics:
kube-state-metrics:
metricsTuning:
excludeMetrics:
- kube_pod_info
test:
attempts: 20
extraQueries:
- query: "kube_pod_info{cluster=\"ci-test-cluster\"}"
type: promql
expect:
count: 0
```
Which allows us to do negative testing for the first time.
> Make it so helm test queries can assert values

- .github/workflows/check-for-dependency-updates.yaml
- .github/workflows/helm-release.yml
- .github/workflows/helm-test.yml
- charts/k8s-monitoring/Makefile
- charts/k8s-monitoring/values.yaml
- examples/cluster-with-pvc/output.yaml
- examples/control-plane-metrics/output.yaml
- examples/custom-config/output.yaml
- examples/custom-metrics-tuning/output.yaml
- examples/default-values/output.yaml
- examples/eks-fargate/output.yaml
- examples/extra-rules/output.yaml
- examples/gke-autopilot/output.yaml
- examples/ibm-cloud/output.yaml
- examples/metrics-only/output.yaml
- examples/otel-metrics-service/output.yaml
- examples/private-image-registry/output.yaml
- examples/proxies/output.yaml
- examples/scrape-intervals/output.yaml
- examples/service-integrations/output.yaml
- examples/specific-namespace/output.yaml
- examples/traces-enabled/output.yaml
- examples/windows-exporter/output.yaml
We should disable these annotations.
In the case that the user changes the default annotation auto discovery annotations to:
```
metrics:
autoDiscover:
annotations:
scrape: "prometheus.io/scrape"
```
It'll discover KSM and Node Exporter services, leading to duplicated metrics.
Fixes #356
> Disable the prometheus.io/scrape annotations on Kube State Metrics and Node Exporter

- examples/traces-enabled/README.md
The traces-enabled values.yaml doesn't include the `extraPorts` anymore because they're part of the default values.yaml.
This just updates the README.md to match.
> Update traces-enabled README to match values.yaml

- charts/k8s-monitoring/templates/_configs.tpl
- charts/k8s-monitoring/templates/agent_config/_processors.river.txt
- examples/custom-metrics-tuning/metrics.river
- examples/custom-metrics-tuning/output.yaml
- examples/metrics-only/metrics.river
- examples/metrics-only/output.yaml
- examples/scrape-intervals/metrics.river
- examples/scrape-intervals/output.yaml
- scripts/lint-configs.sh
- scripts/setup-local-test-cluster.sh
This should make it so the log processor is available in the metrics agent if and only if `logs.enabled=true` and if the receivers are enabled.
Also, improve the lint-config script so it actually tries to run the config file, which will find broken component references in the config file.
Finally, improve the cluster creation script to optionally be able to deploy the k8s-mon chart if you pass a values file to it.
> Fix the inclusion criteria for pod logs processor if pod logs is disabled

- charts/k8s-monitoring/templates/log-service-credentials.yaml
- examples/custom-metrics-tuning/metrics.river
- examples/custom-metrics-tuning/output.yaml
- examples/custom-metrics-tuning/values.yaml
- examples/metrics-only/metrics.river
- examples/metrics-only/output.yaml
- examples/metrics-only/values.yaml
- examples/scrape-intervals/metrics.river
- examples/scrape-intervals/output.yaml
- examples/scrape-intervals/values.yaml
This change means the loki secret is available even if we're only using the receivers for logs. This is helpful for an AppO11y-only deployment of the chart.
> Create the loki secret when logs.enabled is true

- charts/k8s-monitoring/README.md
- charts/k8s-monitoring/README.md.gotmpl
- charts/k8s-monitoring/templates/agent_config/_prometheus_operator_objects.txt
- charts/k8s-monitoring/values.schema.json
- charts/k8s-monitoring/values.yaml
Add label selector for PodMonitor, ServiceMonitor and Probe objects to limit the scraping to only certain targets.
> Add selectors to ServiceMonitor, PodMonitor and Probe objects

- .github/configs/mysql-config.yaml
- .github/workflows/helm-test.yml
- charts/k8s-monitoring/README.md
- charts/k8s-monitoring/ci/ci-2-values.yaml
- charts/k8s-monitoring/ci/ci-integrations-values.yaml
- charts/k8s-monitoring/ci/ci-values.yaml
- charts/k8s-monitoring/templates/hooks/validate-configuration.yaml
- charts/k8s-monitoring/templates/tests/test.yaml
- charts/k8s-monitoring/values.yaml
- examples/cluster-with-pvc/output.yaml
- examples/control-plane-metrics/output.yaml
- examples/custom-config/output.yaml
- examples/custom-metrics-tuning/output.yaml
- examples/default-values/output.yaml
- examples/eks-fargate/output.yaml
- examples/extra-rules/output.yaml
- examples/gke-autopilot/output.yaml
- examples/ibm-cloud/output.yaml
- examples/kube-pod-labels/output.yaml
- examples/logs-only/output.yaml
- examples/metrics-only/output.yaml
- examples/openshift-compatible/output.yaml
- examples/otel-metrics-service/output.yaml
- examples/private-image-registry/output.yaml
- examples/proxies/output.yaml
- examples/scrape-intervals/output.yaml
- examples/service-integrations/output.yaml
- examples/specific-namespace/output.yaml
- examples/traces-enabled/output.yaml
- examples/windows-exporter/output.yaml
Seems to be improving the test reliability
* MySQL clustering enabled to ensure the DPM stays at 1
* Increased test timeout to 10m to ensure that all metrics, logs, and traces are delivered to their data sources.
* Added some values for the different test and validation tasks. This makes them much more configurable
* Wrapped LogQL queries in count_over_time to make sure it goes back in time to when those logs or events occurred.
> Convert test back to a job and break out functionality for the config analysis

- charts/k8s-monitoring/templates/hooks/validate-configuration.yaml
- examples/agent-autoscaling-and-storage/output.yaml
- examples/control-plane-metrics/output.yaml
- examples/custom-config/output.yaml
- examples/custom-metrics-tuning/output.yaml
- examples/custom-pricing/output.yaml
- examples/default-values/output.yaml
- examples/eks-fargate/output.yaml
- examples/extra-rules/output.yaml
- examples/gke-autopilot/output.yaml
- examples/ibm-cloud/output.yaml
- examples/kube-pod-labels/output.yaml
- examples/logs-only/output.yaml
- examples/metrics-only/output.yaml
- examples/openshift-compatible/output.yaml
- examples/otel-metrics-service/output.yaml
- examples/private-image-registry/output.yaml
- examples/proxies/output.yaml
- examples/scrape-intervals/output.yaml
- examples/service-integrations/output.yaml
- examples/specific-namespace/output.yaml
- examples/traces-enabled/output.yaml
- examples/windows-exporter/output.yaml
The hook runs `grafana-agent fmt` which only checks for syntax errors, but it will not catch issues if a component references a component that doesn't exist.
Running `grafana-agent run` will find those... but it actually runs the agent.
By setting `KUBERNETES_SERVICE_HOST` and `KUBERNETES_SERVICE_PORT` to empty values, we can force the agent to fail in a known way. If it fails in that way, we can assume the configuration is "valid" enough to proceed.
> Improve the config validation hook so that it actually runs the agent and finds invalid configurations

- charts/k8s-monitoring/templates/agent_config/_processors.river.txt
The metrics/logs/traces sections are blocks, not statements. Also, fix a missing closing bracket that caused the configuration to break if the user had configured any extra log filters.
> Fix configuration format for filter processor overrides

- .github/configs/updatecli.d/kube-state-metrics.yaml
- .github/configs/updatecli.d/node-exporter.yaml
- .github/configs/updatecli.d/opencost.yaml
- .github/configs/updatecli.d/prometheus-operator-crds.yaml
- .github/configs/updatecli.d/windows-exporter.yaml
Never adjusted the indices after adding Grafana Agent for Events.
Note to reviewer:
Indices 0, 1, and 2 are used by Grafana Agent, agent for events, and agent for logs.
It should match the lines in this file: https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring/Chart.yaml
> Fix Helm chart dependency checking

- charts/k8s-monitoring/templates/agent_config/_profiles_pprof.river.txt
Correct templating for pprof Profiling Enabled, currently its disabled if ebpf is disabled, but it should use `.Values.profiles.pprof.enabled` instead.
> Correct templating for pprof Profiling Enabled

- examples/profiles-enabled/README.md
Correct Title for Profiles Enabled Example, replaces `Traces Enabled` with `Profiles Enabled`
> Correct Title for Profiles Enabled Example

- .github/workflows/helm-test.yml
- scripts/setup-local-test-cluster.sh
The Loki Helm chart version 6.0 and greater installs Loki 3.0. The current values file does not work with the new Loki, and I don't want to hold up work to figure out why.
Eventually, we should make the loki config work with 3.0 and remove this constraint.
> Pin loki chart to the version < Loki 3.0

- .gitignore
- charts/k8s-monitoring/templates/_config_validations.tpl
- charts/k8s-monitoring/templates/_configs.tpl
- charts/k8s-monitoring/values.yaml
- examples/alloy-autoscaling-and-storage/README.md
- examples/alloy-autoscaling-and-storage/output.yaml
- examples/alloy-autoscaling-and-storage/values.yaml
- examples/control-plane-metrics/output.yaml
- examples/custom-config/output.yaml
- examples/custom-pricing/output.yaml
- examples/default-values/output.yaml
- examples/extra-rules/output.yaml
- examples/gke-autopilot/output.yaml
- examples/ibm-cloud/output.yaml
- examples/kube-pod-labels/output.yaml
- examples/logs-only/output.yaml
- examples/openshift-compatible/output.yaml
- examples/otel-metrics-service/output.yaml
- examples/private-image-registry/output.yaml
- examples/profiles-enabled/output.yaml
- examples/proxies/output.yaml
- examples/service-integrations/output.yaml
- examples/specific-namespace/output.yaml
- examples/traces-enabled/output.yaml
- examples/windows-exporter/output.yaml
- tests/spec/fixtures/invalid-logs-config-volumes-and-clustering-values.yaml
- tests/spec/invalid-logs-configurations_spec.sh
Move PodLogs control to the primary alloy, which does use clustering.
Also add some instructions for setting the storage path for logs instance.
> Turn off clustering for log gathering alloy

- examples/service-integrations/mysql-config.yaml
Corrects `declare "mysql"` to `declare "metrics"` in mysql's k8s ConfigMap
See:
https://github.com/grafana/k8s-monitoring-helm/blob/98bc370a8bf7b340d3e71d535e5301579f3b226d/examples/service-integrations/metrics.alloy#L814-L818
https://github.com/grafana/k8s-monitoring-helm/blob/98bc370a8bf7b340d3e71d535e5301579f3b226d/examples/service-integrations/logs.alloy#L151
> [examples] Corrects COMPONENT_NAME in mysql's k8s ConfigMap

- charts/k8s-monitoring/templates/platform_specific/openshift/security-context-constraint.yaml
- examples/openshift-compatible/README.md
- examples/openshift-compatible/output.yaml
- examples/openshift-compatible/values.yaml
This creates three security context constraints objects now, one for each Alloy instance. The code does template once and invokes that template three times (the logs template will enable hostpath permissions if it's using volume based log gathering)
It does not set the user id to non-root.
It does add a set of capabilities that was listed in another issue. At some point, I'll need to sync with the alloy team for the minimal set required here.
> Update OpenShift platform and examples

- charts/k8s-monitoring/Chart.yaml
- charts/k8s-monitoring/README.md
- charts/k8s-monitoring/values.yaml
I've noticed Grafana Cloud Kubernetes monitoring OpenCost pod started to silently fail with following error:
```
ERR Failed to query prometheus at https://prometheus-prod-01-eu-west-0.grafana.net/api/prom. Error: Prometheus communication error: 401 (Unauthorized)
...
Body: '{"status":"error","error":"authentication error: no credentials provided"}
```
Pods starts just fine, but OpenCost can't connect to Grafana Cloud Prometheus endpoint. And then pods will produce more error logs:
```
0) Errors:
Request Error: Prometheus communication error: 401 (Unauthorized) URL: 'https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/api/v1/query ...
Parse Error: Prometheus communication error: ...
```
After digging into this I've found out that OpenCost chart which this repo uses …
> Fix OpenCost Prometheus existing secret fetching

- charts/k8s-monitoring/templates/_configs.tpl
- charts/k8s-monitoring/templates/alloy_config/_cluster_events.alloy.txt
- charts/k8s-monitoring/templates/alloy_config/_operator_objects.txt
- charts/k8s-monitoring/templates/alloy_config/_pod_logs_processor.alloy.txt
Even though this functionality was [fixed in 3.14](https://github.com/helm/helm/issues/5979#issuecomment-2108701112), some systems (like ArgoCD) might not be able to upgrade so quickly or easily.
Notes for reviewers: `.` is the current context, which gets modified by `with` or with `range`, `$` is always the top context. It's just good practice to use `$`, which is why this one didn't need to change: `charts/k8s-monitoring/templates/extra-manifests.yaml`
> Always call tpl outside of with blocks to preserve backwards compatibility

- charts/k8s-monitoring/templates/_configs.tpl
- examples/logs-journal/metrics.alloy
- examples/logs-journal/output.yaml
Without this, if the user enables the zipkin receiver, but not otlp receivers, the receiver pipelines will handle and pass log components, but will have no log destination at the end of the pipeline.
It doesn't really hurt much to enable these components if they're doing no work. But I wanted to avoid adding more and more complicated logic to determine if they needed to be included.
> Add log components if logs are enabled

- charts/k8s-monitoring/README.md
- charts/k8s-monitoring/templates/hooks/validate-configuration.yaml
- charts/k8s-monitoring/templates/tests/test.yaml
- charts/k8s-monitoring/values.schema.json
- charts/k8s-monitoring/values.yaml
Solves an issue when installing to a cluster where the default service account is not usable or prohibited.
> Add the ability to set the Service Account names

- charts/k8s-monitoring/templates/grafana-agent-receiver-service.yaml
As far as I can tell, this is the only thing that prevents deploying on 1.19
> Only use internalTrafficPolicy: if on Kubernetes vesrion 1.26 or later

- charts/k8s-monitoring/README.md
- charts/k8s-monitoring/templates/_config_validations.tpl
- charts/k8s-monitoring/values.yaml
We cannot force Alloy to change its stability level, but we can warn the user to enable it.
> Add config validation to check for liveDebugging without the experimental stability level

- charts/k8s-monitoring/templates/alloy_config/_profiles_java.alloy.txt
- examples/application-observability/output.yaml
- examples/application-observability/profiles.alloy
- examples/profiles-enabled/output.yaml
- examples/profiles-enabled/profiles.alloy
Before, we were finding java processes by:
1. discovery.kubernetes to get the pods on the same node, and filter by namespace
2. discovery.process to merge those pods with process data
3. discovery.relabel to filter to java processes and set labels
The problem is that `discovery.process` does not just get process info for the pods found in step 1, it returns a list joined with both prods and processes ([docs](https://grafana.com/docs/alloy/latest/reference/components/discovery/discovery.process/#targets-joining)).
This change re-filters in the `discovery.relabel` component to only things that are pods (so, only get kubernetes processes) and the namespace filter again.
> Re-filter after discovery.process to remove any non-kubernetes java processes

- charts/k8s-monitoring/templates/alloy_config/_journal_logs_discovery.alloy.txt
- examples/logs-journal/logs.alloy
- examples/logs-journal/output.yaml
Fixes this bug:
```
Error: /etc/alloy/config.alloy:181:20: "false" should be bool, got string
180 |   path = "/var/log/journal"
181 |   format_as_json = "false"
|                    ^^^^^^^
182 |   max_age = "8h"
```
> Journal logging's format_as_json needs to be a boolean, not a string

- charts/k8s-monitoring/README.md
- charts/k8s-monitoring/templates/alloy_config/_logs_service_loki.alloy.txt
- charts/k8s-monitoring/templates/alloy_config/_metrics_service_remote_write.alloy.txt
- charts/k8s-monitoring/templates/log-service-credentials.yaml
- charts/k8s-monitoring/templates/metrics-service-credentials.yaml
- charts/k8s-monitoring/values.schema.json
- charts/k8s-monitoring/values.yaml
Fixes https://github.com/grafana/k8s-monitoring-helm/issues/658
- [prometheus.remote_write](https://grafana.com/docs/alloy/latest/reference/components/prometheus/prometheus.remote_write/?pg=oss-alloy&plcmt=hero-btn-3#oauth2-block)
- [loki.write](https://grafana.com/docs/alloy/latest/reference/components/loki/loki.write/?pg=oss-alloy&plcmt=hero-btn-3#oauth2-block) 
- Prometheus remote write OAuth2 support.
- Loki write OAuth2 support.
> feat: initial oauth2 support

- charts/k8s-monitoring/templates/alloy_config/_logs_service_loki.alloy.txt
- charts/k8s-monitoring/templates/alloy_config/_metrics_service_remote_write.alloy.txt
- charts/k8s-monitoring/templates/log-service-credentials.yaml
- charts/k8s-monitoring/templates/metrics-service-credentials.yaml
Thanks for the fast review & merge of #678. Sadly I introduced couple of bugs (I thought the configuration language was HCL, but it's not, it only looks kinda like it :smiling_face_with_tear:)
**Changes:**
- Correct format of `endpoint_params` object.
- Typo in secret by using `ID` instead of `Id`.
---
For input:
```yaml
externalServices:
loki:
host: "https:/example.org"
authMode: "oauth2"
oauth2:
tokenURL: "https://example.org"
clientId: "example"
clientSecretFile: "/var/run/secrets/kubernetes.io/serviceaccount/token"
endpointParams:
grant_type: "client_credentials"
client_assertion_type: "urn:ietf:params:oauth:client-assertion-type:jwt-bearer"
```
Example of broken version config:
```
loki.write "logs_service" {
endpoint {
url = …
```
> fix(oauth2): correct object format, Id instead of ID

- charts/k8s-monitoring/README.md
- charts/k8s-monitoring/templates/alloy_config/_annotation_autodiscovery.alloy.txt
- charts/k8s-monitoring/values.schema.json
- charts/k8s-monitoring/values.yaml
This is to allow users to disable or enable the usage of sa bearer token in auto discovery, this was add on version 1.3.0, but users don't have a option to disable it if this is not needed. Unauthenticated services using Service Account without token or services not behind something like kube-rbac-proxy is returning 400 error.
https://github.com/grafana/k8s-monitoring-helm/pull/580
> Adding a conditional to enable or disable bearer token in auto discovery

- charts/k8s-monitoring-v1/values.yaml
This avoids an error when skipping configmap creation but not naming it. Only happens with specific versions of helm, but now it'll work everywhere.
Field in the beyla chart:
https://github.com/grafana/beyla/blob/main/charts/beyla/values.yaml#L183-L184
ConfigMap check in beyla chart:
https://github.com/grafana/beyla/blob/main/charts/beyla/templates/configmap.yaml#L1-L5
> Use the new skipConfigMapCheck field

- charts/k8s-monitoring/docs/examples/extra-rules/alloy-metrics.alloy
- charts/k8s-monitoring/docs/examples/extra-rules/output.yaml
- charts/k8s-monitoring/templates/destinations/_destination_prometheus.tpl
Noticed that the examples showed extraLabels instead of externalLabels. When I changed my values to externalLabels I was getting an EOF config error when adding the labels. The block was not closed correctly. 
I'm also happy to change the documentation to externalLabels as the argument is called external_labels in the documenation. https://grafana.com/docs/alloy/latest/reference/components/prometheus/prometheus.remote_write/#arguments
> fix: prom destination template config error and change externalLabels to extraLabels

- charts/feature-cluster-metrics/README.md
- charts/feature-cluster-metrics/schema-mods/types-and-enums.json
- charts/feature-cluster-metrics/values.schema.json
- charts/feature-cluster-metrics/values.yaml
I noticed this when playing around with the k8s-monitoring v2 chart - the apiserver enabled field wasn't set to default to `false` in the values yaml, so the generated schema only allowed "null" for the value.
> Set apiserver enabled default to false in feature-cluster-metrics values

- charts/k8s-monitoring/destinations/loki-values.yaml
- charts/k8s-monitoring/destinations/otlp-values.yaml
- charts/k8s-monitoring/destinations/prometheus-values.yaml
- charts/k8s-monitoring/destinations/pyroscope-values.yaml
- charts/k8s-monitoring/docs/destinations/loki.md
- charts/k8s-monitoring/docs/destinations/otlp.md
- charts/k8s-monitoring/docs/destinations/prometheus.md
- charts/k8s-monitoring/docs/destinations/pyroscope.md
- charts/k8s-monitoring/schema-mods/definitions/loki-destination.schema.json
- charts/k8s-monitoring/schema-mods/definitions/otlp-destination.schema.json
- charts/k8s-monitoring/schema-mods/definitions/prometheus-destination.schema.json
- charts/k8s-monitoring/schema-mods/definitions/pyroscope-destination.schema.json
- charts/k8s-monitoring/templates/destinations/_destination_loki.tpl
- charts/k8s-monitoring/templates/destinations/_destination_otlp.tpl
- charts/k8s-monitoring/templates/destinations/_destination_prometheus.tpl
- charts/k8s-monitoring/templates/destinations/_destination_pyroscope.tpl
- charts/k8s-monitoring/values.schema.json
Adds a `urlFrom` values for destinations in k8s-monitoring-v2. 
This allows setting the URL using unquoted raw config, which can allow setting it from an environment variable, among other things. 
In my specific use case, this is useful when using k8s-monitoring as a subchart and wanting to set a top-level value URL that applies for all destination endpoints. Basically, wrapping `k8s-monitoring` and exposing a simplified set of values for consumers of our system. A simplified example below:
```yaml
observabilityGatewayUrl: ""
k8s-monitoring:
destinations:
- name: mimir
type: prometheus
urlFrom: env("OBSERVABILITY_METRICS_URL")
- name: loki
type: loki
urlFrom: env("OBSERVABILITY_LOGS_URL")
alloy-metrics:
alloy:
envFrom:
- configMapRef:
name: observability-config
alloy-logs:
alloy:
envFrom: …
```
> Add urlFrom value for k8s-monitoring v2 destinations

- charts/k8s-monitoring-v1/README.md
- charts/k8s-monitoring-v1/docs/examples/otel-metrics-service/metrics.alloy
- charts/k8s-monitoring-v1/docs/examples/otel-metrics-service/output.yaml
- charts/k8s-monitoring-v1/templates/alloy_config/_logs_service_loki.alloy.txt
- charts/k8s-monitoring-v1/templates/alloy_config/_logs_service_otlp.alloy.txt
- charts/k8s-monitoring-v1/templates/alloy_config/_metrics_service_otlp.alloy.txt
- charts/k8s-monitoring-v1/templates/log-service-credentials.yaml
- charts/k8s-monitoring-v1/values.schema.json
- charts/k8s-monitoring-v1/values.yaml
> Add bearer token support for loki and for metrics over otlp

- charts/k8s-monitoring/docs/examples/auth/bearer-token/output.yaml
- charts/k8s-monitoring/docs/examples/auth/embedded-secrets/output.yaml
- charts/k8s-monitoring/docs/examples/auth/external-secrets/output.yaml
- charts/k8s-monitoring/docs/examples/auth/sigv4/output.yaml
- charts/k8s-monitoring/docs/examples/autoscaling/output.yaml
- charts/k8s-monitoring/docs/examples/collector-storage/output.yaml
- charts/k8s-monitoring/docs/examples/extra-rules/output.yaml
- charts/k8s-monitoring/docs/examples/features/annotation-autodiscovery/default/output.yaml
- charts/k8s-monitoring/docs/examples/features/annotation-autodiscovery/prom-annotations/output.yaml
- charts/k8s-monitoring/docs/examples/features/applicaiton-observability/default/output.yaml
- charts/k8s-monitoring/docs/examples/features/cluster-metrics/control-plane-monitoring/output.yaml
- charts/k8s-monitoring/docs/examples/features/cluster-metrics/default/output.yaml
- charts/k8s-monitoring/docs/examples/features/integrations/alloy/output.yaml
- charts/k8s-monitoring/docs/examples/features/integrations/cert-manager/output.yaml
- charts/k8s-monitoring/docs/examples/features/integrations/etcd/output.yaml
- charts/k8s-monitoring/docs/examples/features/integrations/mysql/output.yaml
- charts/k8s-monitoring/docs/examples/features/prometheus-operator-objects/default/output.yaml
- charts/k8s-monitoring/docs/examples/metrics-tuning/output.yaml
- charts/k8s-monitoring/docs/examples/platforms/azure-aks/output.yaml
- charts/k8s-monitoring/docs/examples/platforms/eks-fargate/output.yaml
- charts/k8s-monitoring/docs/examples/platforms/gke-autopilot/output.yaml
- charts/k8s-monitoring/docs/examples/private-image-registries/output.yaml
- charts/k8s-monitoring/docs/examples/proxies/output.yaml
- charts/k8s-monitoring/templates/features/_feature_self_reporting.tpl
Also, don't include the platform label if it was not set
> Fix the self report destination ecosystem.

- .github/workflows/auto-approve-chart-deps.yml
- .github/workflows/auto-approve-dependabot.yml
New GitHub workflows:
- `.github/workflows/auto-approve-chart-deps.yml` should auto-approve PRs created by the "Check for dependency updates" workflow.
- `.github/workflows/auto-approve-dependabot.yml` should auto-approve PRs created by dependabot
Based on this doc:
- https://github.com/dependabot/fetch-metadata?tab=readme-ov-file#auto-approving
If you like this look of this, auto-merge can follow in a separate PR - but this first requires a repo setting update to support that. See:
- https://github.com/dependabot/fetch-metadata?tab=readme-ov-file#enabling-auto-merge
> ci: adds auto-approve workflows for deps

- charts/k8s-monitoring-v1/templates/alloy_config/_operator_objects.txt
We should determine clustering based on alloy
> PodLog objects always go onto the alloy instance, not alloy-logs

- charts/k8s-monitoring/docs/Migration.md
> Fix the migration guide's extaConfg table

- .github/workflows/auto-approve-chart-deps.yml
Looks like #949 and #950 were not automatically approved. I think it's because although the commit is by `petewall`, it is actually `github-actions[bot]` that creates the PR.
> fix: chart dep PR user is github-actions[bot]

- .github/workflows/platform-test.yml
- charts/k8s-monitoring-test/README.md
- charts/k8s-monitoring-test/templates/tests/test-pod.yaml
- charts/k8s-monitoring-test/values.yaml
- charts/k8s-monitoring/destinations/otlp-values.yaml
- charts/k8s-monitoring/docs/destinations/otlp.md
- charts/k8s-monitoring/docs/examples/destinations/otlp-gateway/README.md
- charts/k8s-monitoring/docs/examples/destinations/otlp-gateway/alloy-logs.alloy
- charts/k8s-monitoring/docs/examples/destinations/otlp-gateway/alloy-metrics.alloy
- charts/k8s-monitoring/docs/examples/destinations/otlp-gateway/description.txt
- charts/k8s-monitoring/docs/examples/destinations/otlp-gateway/output.yaml
- charts/k8s-monitoring/docs/examples/destinations/otlp-gateway/values.yaml
- charts/k8s-monitoring/templates/destinations/_destination_otlp.tpl
- charts/k8s-monitoring/tests/platform/otlp-gateway/.envrc
- charts/k8s-monitoring/tests/platform/otlp-gateway/.rendered/output.yaml
- charts/k8s-monitoring/tests/platform/otlp-gateway/deployments/grafana-cloud-credentials.yaml
- charts/k8s-monitoring/tests/platform/otlp-gateway/deployments/test-variables.yaml
- charts/k8s-monitoring/tests/platform/otlp-gateway/grafana-cloud-credentials.yaml
- charts/k8s-monitoring/tests/platform/otlp-gateway/test-manifest.yaml
- charts/k8s-monitoring/tests/platform/otlp-gateway/test-values.yaml
- charts/k8s-monitoring/tests/platform/otlp-gateway/test-variables.yaml
- charts/k8s-monitoring/tests/platform/otlp-gateway/values.yaml
- scripts/run-integration-test.sh
- scripts/schema-gen.sh
* Adds an example on how to use the [Grafana Cloud OTLP gateway](https://grafana.com/docs/grafana-cloud/send-data/otlp/send-data-otlp/) (also called the otlp endpoint).
* Adds a platform test that sends metrics and logs to Grafana Cloud, using the gateway.
* Adds a `valueFrom` field to the OTLP destination processors, that lets be set values based on environment variables.
> Add example and platform test to check the otlp gateway

- charts/k8s-monitoring/templates/secrets/_helpers.tpl
When using `username_key` and `password_key` the helper tries to verify the key in the prometheus destination matches. Fetching this key fails, as the code currently passes `.auth.password` to the helper. The helper splits the string on `.` then tries to drill down into the object, but as it splits on `.` it gets an initial `nil` due to the leading period. This means the code always gives the default key, which does not work.
This fix makes the function more robust by skipping the initial nil.
> Fix nil issue when key passed to get helpers starts with .

- charts/k8s-monitoring/tests/integration/statsd/deployments/grafana.yaml
- charts/k8s-monitoring/tests/integration/statsd/deployments/prometheus.yaml
- charts/k8s-monitoring/tests/integration/statsd/deployments/query-test.yaml
- charts/k8s-monitoring/tests/integration/statsd/deployments/statsd-example.yaml
- charts/k8s-monitoring/tests/integration/statsd/values.yaml
Originally made to test a customer situation, but found it useful to show an alternative use of the alloy-receiver.
> Add test showing how to use extraConfig and statsd

- charts/k8s-monitoring/tests/platform/eks-with-windows/.rendered/output.yaml
- charts/k8s-monitoring/tests/platform/eks-with-windows/Makefile
- charts/k8s-monitoring/tests/platform/eks-with-windows/deployments/query-test.yaml
- charts/k8s-monitoring/tests/platform/eks-with-windows/values.yaml
- charts/k8s-monitoring/tests/platform/gke-autopilot/Makefile
- charts/k8s-monitoring/tests/platform/grafana-cloud-features/k8s-monitoring/Makefile
- charts/k8s-monitoring/tests/platform/otlp-gateway/Makefile
- charts/k8s-monitoring/tests/platform/remote-config/Makefile
Also add a run-test target to platform tests Makefiles to make it easier to run locally.
Adding them to the EKS test because the GKE Autopilot cluster or any Kind cluster wont have journal logs.
> Add the Node Logs feature to a test.

- charts/k8s-monitoring/docs/examples/features/integrations/mysql/README.md
- charts/k8s-monitoring/docs/examples/features/integrations/mysql/description.txt
- charts/k8s-monitoring/tests/integration/anntoation-autodiscovery/deployments/query-test.yaml
- charts/k8s-monitoring/tests/integration/auth/deployments/query-test.yaml
- charts/k8s-monitoring/tests/integration/auto-instrumentation/deployments/query-test.yaml
- charts/k8s-monitoring/tests/integration/cluster-monitoring/deployments/query-test.yaml
- charts/k8s-monitoring/tests/integration/control-plane-monitoring/deployments/query-test.yaml
- charts/k8s-monitoring/tests/integration/integration-cert-manager/deployments/query-test.yaml
- charts/k8s-monitoring/tests/integration/integration-grafana/deployments/query-test.yaml
- charts/k8s-monitoring/tests/integration/integration-loki/deployments/query-test.yaml
- charts/k8s-monitoring/tests/integration/integration-mysql/deployments/query-test.yaml
- charts/k8s-monitoring/tests/integration/profiling/deployments/query-test.yaml
- charts/k8s-monitoring/tests/integration/statsd/deployments/query-test.yaml
- scripts/run-cluster-test.sh
This should help ensure that the DBs are online and ready for queries before deploying the chart that will run the queries
> Add dependencies on the databases for the test chart.

- charts/k8s-monitoring-v1/docs/examples/environment-variables/metrics.alloy
- charts/k8s-monitoring-v1/docs/examples/environment-variables/output.yaml
- charts/k8s-monitoring-v1/docs/examples/specific-namespace/metrics.alloy
- charts/k8s-monitoring-v1/docs/examples/specific-namespace/output.yaml
- charts/k8s-monitoring-v1/templates/alloy_config/_operator_objects.txt
- charts/k8s-monitoring/docs/examples/extra-rules/README.md
- charts/k8s-monitoring/docs/examples/extra-rules/alloy-metrics.alloy
- charts/k8s-monitoring/docs/examples/extra-rules/output.yaml
- charts/k8s-monitoring/docs/examples/extra-rules/values.yaml
In v1: relabeling rules
In v2: processing rules
Fixing some issues in both cases. In v1 it's a functional bug. In v2, it was just in documentation.
> Fix misnaming of relabeling and processing rules

- charts/k8s-monitoring/docs/examples/destinations/otlp-gateway/README.md
- charts/k8s-monitoring/docs/examples/destinations/otlp-gateway/description.txt
> Fix otlp-gateway readme typo

- charts/k8s-monitoring/docs/examples/istio-service-mesh/README.md
- charts/k8s-monitoring/docs/examples/istio-service-mesh/alloy-metrics.alloy
- charts/k8s-monitoring/docs/examples/istio-service-mesh/description.txt
- charts/k8s-monitoring/docs/examples/istio-service-mesh/output.yaml
- charts/k8s-monitoring/docs/examples/istio-service-mesh/values.yaml
- charts/k8s-monitoring/tests/integration/istio-service-mesh/.rendered/output.yaml
- charts/k8s-monitoring/tests/integration/istio-service-mesh/deployments/default-namespace-label.yaml
- charts/k8s-monitoring/tests/integration/istio-service-mesh/deployments/grafana.yaml
- charts/k8s-monitoring/tests/integration/istio-service-mesh/deployments/isitio.yaml
- charts/k8s-monitoring/tests/integration/istio-service-mesh/deployments/loki.yaml
- charts/k8s-monitoring/tests/integration/istio-service-mesh/deployments/prometheus.yaml
- charts/k8s-monitoring/tests/integration/istio-service-mesh/deployments/query-test.yaml
- charts/k8s-monitoring/tests/integration/istio-service-mesh/values.yaml
- scripts/run-cluster-test.sh
The Alloy cluster's headless service needs a new port name, not `http`, because the default name causes a problem:
https://istio.io/latest/docs/ops/common-problems/network-issues/#503-error-while-accessing-headless-services
> Add test and example showing how to work with istio service mesh

- charts/k8s-monitoring/templates/destinations/_destination_prometheus.tpl
fixup to remove access_key and secret_key rendering if they are not already defined in values.yaml.  Fixes #1122
> fix sigv4 rendering in Prometheus template for #1122

- charts/k8s-monitoring/templates/destinations/_destination_loki.tpl
- charts/k8s-monitoring/templates/destinations/_destination_otlp.tpl
- charts/k8s-monitoring/templates/destinations/_destination_prometheus.tpl
- charts/k8s-monitoring/templates/destinations/_destination_pyroscope.tpl
Just like `caFile`, if these are provided, it'll use them instead of trying to find them in the secret.
> Actually use certFile and keyFile settings

- charts/k8s-monitoring-v1/docs/examples/beyla/README.md
Users often don't know where to extend/override the Beyla configuration. Extending the example with a placeholder example.
> Extend Beyla configuration example

- .gitignore
- CONTRIBUTING.md
Looks like this `run-integration-test.sh` script was deleted in #961 and replaced by `run-cluster-test.sh`
> update CONTRIBUTING.md integration test directions

- charts/k8s-monitoring/charts/feature-application-observability/templates/_receiver_jaeger.tpl
- charts/k8s-monitoring/charts/feature-application-observability/tests/default_test.yaml
- charts/k8s-monitoring/charts/feature-application-observability/tests/jaeger_test.yaml
- charts/k8s-monitoring/docs/examples/auth/bearer-token/alloy-receiver.alloy
- charts/k8s-monitoring/docs/examples/auth/bearer-token/output.yaml
- charts/k8s-monitoring/docs/examples/auth/external-secrets/alloy-receiver.alloy
- charts/k8s-monitoring/docs/examples/auth/external-secrets/output.yaml
- charts/k8s-monitoring/docs/examples/meta-monitoring/README.md
- charts/k8s-monitoring/docs/examples/meta-monitoring/alloy-receiver.alloy
- charts/k8s-monitoring/docs/examples/meta-monitoring/alloy-singleton.alloy
- charts/k8s-monitoring/docs/examples/meta-monitoring/output.yaml
- charts/k8s-monitoring/docs/examples/meta-monitoring/values.yaml
- charts/k8s-monitoring/templates/destinations/_destination_otlp.tpl
- charts/k8s-monitoring/templates/destinations/_destination_validations.tpl
- charts/k8s-monitoring/templates/features/_feature_application_observability.tpl
- Set jaeger port names
- Setting: `receivers.jaeger.thriftHttp.enabled` would not config the receiver as it didn't satisfy the condition
- The jaeger ports were rendering 0, as the dictionary was passed to | int, not the port
> fix: alloy-receiver jaeger bugs

- charts/k8s-monitoring/charts/feature-pod-logs/templates/_common_log_processing.alloy.tpl
- charts/k8s-monitoring/charts/feature-pod-logs/tests/default_test.yaml
- charts/k8s-monitoring/docs/examples/extra-rules/alloy-logs.alloy
- charts/k8s-monitoring/docs/examples/extra-rules/output.yaml
- charts/k8s-monitoring/docs/examples/features/integrations/grafana/alloy-logs.alloy
- charts/k8s-monitoring/docs/examples/features/integrations/grafana/output.yaml
- charts/k8s-monitoring/docs/examples/features/integrations/loki/alloy-logs.alloy
- charts/k8s-monitoring/docs/examples/features/integrations/loki/output.yaml
- charts/k8s-monitoring/docs/examples/features/integrations/mimir/alloy-logs.alloy
- charts/k8s-monitoring/docs/examples/features/integrations/mimir/output.yaml
- charts/k8s-monitoring/docs/examples/features/integrations/mysql/alloy-logs.alloy
- charts/k8s-monitoring/docs/examples/features/integrations/mysql/output.yaml
- charts/k8s-monitoring/docs/examples/meta-monitoring/README.md
- charts/k8s-monitoring/docs/examples/meta-monitoring/alloy-singleton.alloy
- charts/k8s-monitoring/docs/examples/meta-monitoring/output.yaml
- charts/k8s-monitoring/docs/examples/meta-monitoring/values.yaml
- charts/k8s-monitoring/tests/integration/integration-grafana/.rendered/output.yaml
- charts/k8s-monitoring/tests/integration/integration-loki/.rendered/output.yaml
- charts/k8s-monitoring/tests/integration/integration-mysql/.rendered/output.yaml
The label keep stage was being inserted before extraLogProcessingStages.  When integrations create labels as part of their processing, those labels may or may not be desired to be kept be the user.   Making this change eliminates the need to have each integration define its own set of labels to keep.
> fix: pod logs label keep

- charts/k8s-monitoring/destinations/loki-values.yaml
- charts/k8s-monitoring/docs/destinations/loki.md
- charts/k8s-monitoring/schema-mods/definitions/loki-destination.schema.json
- charts/k8s-monitoring/templates/destinations/_destination_loki.tpl
- charts/k8s-monitoring/tests/integration/split-destinations/.rendered/output.yaml
- charts/k8s-monitoring/tests/integration/split-destinations/deployments/dbs.yaml
- charts/k8s-monitoring/tests/integration/split-destinations/deployments/grafana.yaml
- charts/k8s-monitoring/tests/integration/split-destinations/deployments/loki.yaml
- charts/k8s-monitoring/tests/integration/split-destinations/deployments/prometheus.yaml
- charts/k8s-monitoring/tests/integration/split-destinations/deployments/query-test.yaml
- charts/k8s-monitoring/tests/integration/split-destinations/deployments/workloads.yaml
- charts/k8s-monitoring/tests/integration/split-destinations/kind-cluster-config.yaml
- charts/k8s-monitoring/tests/integration/split-destinations/values.yaml
- charts/k8s-monitoring/values.schema.json
Provide an integration test that shows how to use them
> Add the ability to specify processing stages per loki destination

- charts/k8s-monitoring/templates/destinations/_destination_validations.tpl
Fixes an issue reported by @gouthamve that was preventing v1 tempo users from upgrading by forcing OTLP http when GRPC should be allowed for non otlp-gateway-* urls
> Added otlp-gateway as part of validation check

- charts/k8s-monitoring/templates/secrets/test/secrets.yaml
- charts/k8s-monitoring/tests/unittest_secrets_test.yaml
This better handles when `testing` is empty, a boolean, or a string.
> Better type comparison for the secrets unittest

- charts/k8s-monitoring/templates/receiver-service.yaml
For now `app.kubernetes.io/name` is set to `k8s-monitoring` instead of `alloy-receiver`, so no alloy-receiver's pods are matched by extraService's selector.
> fix: receiver extraService selector

- charts/k8s-monitoring/charts/feature-application-observability/templates/_processor_k8sattributes.tpl
- charts/k8s-monitoring/charts/feature-application-observability/tests/default_test.yaml
- charts/k8s-monitoring/charts/feature-application-observability/tests/interval_test.yaml
- charts/k8s-monitoring/charts/feature-application-observability/tests/memorylimiter_test.yaml
- charts/k8s-monitoring/charts/feature-application-observability/tests/spanlogs_test.yaml
- charts/k8s-monitoring/charts/feature-application-observability/tests/spanmetrics_test.yaml
- charts/k8s-monitoring/docs/examples/auth/bearer-token/alloy-receiver.alloy
- charts/k8s-monitoring/docs/examples/auth/bearer-token/output.yaml
- charts/k8s-monitoring/docs/examples/auth/embedded-secrets/alloy-receiver.alloy
- charts/k8s-monitoring/docs/examples/auth/embedded-secrets/output.yaml
- charts/k8s-monitoring/docs/examples/auth/external-secrets/alloy-receiver.alloy
- charts/k8s-monitoring/docs/examples/auth/external-secrets/output.yaml
- charts/k8s-monitoring/docs/examples/features/application-observability/default/alloy-receiver.alloy
- charts/k8s-monitoring/docs/examples/features/application-observability/default/output.yaml
- charts/k8s-monitoring/docs/examples/features/auto-instrumentation/beyla-metrics-and-traces/alloy-receiver.alloy
- charts/k8s-monitoring/docs/examples/features/auto-instrumentation/beyla-metrics-and-traces/output.yaml
- charts/k8s-monitoring/docs/examples/meta-monitoring/alloy-receiver.alloy
- charts/k8s-monitoring/docs/examples/meta-monitoring/output.yaml
- charts/k8s-monitoring/docs/examples/pod-labels-and-annotations/alloy-receiver.alloy
- charts/k8s-monitoring/docs/examples/pod-labels-and-annotations/output.yaml
- charts/k8s-monitoring/docs/examples/proxies/alloy-receiver.alloy
- charts/k8s-monitoring/docs/examples/proxies/output.yaml
- charts/k8s-monitoring/tests/integration/auto-instrumentation/.rendered/output.yaml
- charts/k8s-monitoring/tests/platform/grafana-cloud/app-observability/.rendered/output.yaml
Using `k8s.pod.ip` and `k8s.pod.uid` resource attributes might be a better defaults for `k8sattributes` processor. Especially because `internalTrafficPolicy` on alloy-receiver's service is set to `Cluster` by default, so there is a chance that alloy would see a node ip address instead of pod's one and wouldn't be able to add k8s attributes.
This sources are also added by default in [Opentelemetry Collector chart](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/opentelemetry-collector-0.116.0/charts/opentelemetry-collector/templates/_config.tpl#L215).
> feat: add pod_association sources

- charts/k8s-monitoring/templates/features/_feature_application_observability.tpl
In my case I'd like to start with sending otlp metrics and forward them to prometheus remote write endpoint. I've set `applicationObservability.logs.enabled` and `applicationObservability.traces.enabled` to `false` but I still have to add fake destinations for logs and traces to pass validation.
> feat: validate destinations only for enabled signals

- charts/k8s-monitoring/README.md
- charts/k8s-monitoring/values.schema.json
- charts/k8s-monitoring/values.yaml
When leveraging the Application Observability functionality, you need to specify the receivers block so Alloy knows what is enabled (i.e. otlp, grpc etc).
The current Values file does not have receivers: {}, and you only find out it's needed via the Validation when running Helm.
This PR simply just adds it in with no config, but links back to the documentation. There's also a fix on the type of what the function is for (currently states pod logs, now updated to enabling the receiving of application observability).
> Add Receivers block to App O11y in Values

- charts/k8s-monitoring/charts/feature-cluster-metrics/README.md
- charts/k8s-monitoring/charts/feature-cluster-metrics/templates/_kube_controller_manager.alloy.tpl
- charts/k8s-monitoring/charts/feature-cluster-metrics/templates/_kube_proxy.alloy.tpl
- charts/k8s-monitoring/charts/feature-cluster-metrics/templates/_kube_scheduler.alloy.tpl
- charts/k8s-monitoring/charts/feature-cluster-metrics/values.schema.json
- charts/k8s-monitoring/charts/feature-cluster-metrics/values.yaml
The selector label for metrics scraping of K8s control-plane components is currently hardcoded in templates. This PR allows specifying a custom selector label for the kube-scheduler, kube-proxy and kube-controller-manager components.
> Allow specifying custom selector label for control-plane components

- charts/k8s-monitoring/charts/feature-application-observability/templates/_processor_k8sattributes.tpl
- charts/k8s-monitoring/charts/feature-application-observability/tests/default_test.yaml
- charts/k8s-monitoring/charts/feature-application-observability/tests/interval_test.yaml
- charts/k8s-monitoring/charts/feature-application-observability/tests/memorylimiter_test.yaml
- charts/k8s-monitoring/charts/feature-application-observability/tests/resourcedetection_test.yaml
- charts/k8s-monitoring/charts/feature-application-observability/tests/spanlogs_test.yaml
- charts/k8s-monitoring/charts/feature-application-observability/tests/spanmetrics_test.yaml
- charts/k8s-monitoring/docs/examples/auth/bearer-token/alloy-receiver.alloy
- charts/k8s-monitoring/docs/examples/auth/bearer-token/output.yaml
- charts/k8s-monitoring/docs/examples/auth/embedded-secrets/alloy-receiver.alloy
- charts/k8s-monitoring/docs/examples/auth/embedded-secrets/output.yaml
- charts/k8s-monitoring/docs/examples/auth/external-secrets/alloy-receiver.alloy
- charts/k8s-monitoring/docs/examples/auth/external-secrets/output.yaml
- charts/k8s-monitoring/docs/examples/features/application-observability/default/alloy-receiver.alloy
- charts/k8s-monitoring/docs/examples/features/application-observability/default/output.yaml
- charts/k8s-monitoring/docs/examples/features/auto-instrumentation/beyla-metrics-and-traces/alloy-receiver.alloy
- charts/k8s-monitoring/docs/examples/features/auto-instrumentation/beyla-metrics-and-traces/output.yaml
- charts/k8s-monitoring/docs/examples/meta-monitoring/alloy-receiver.alloy
- charts/k8s-monitoring/docs/examples/meta-monitoring/output.yaml
- charts/k8s-monitoring/docs/examples/pod-labels-and-annotations/alloy-receiver.alloy
- charts/k8s-monitoring/docs/examples/pod-labels-and-annotations/output.yaml
- charts/k8s-monitoring/docs/examples/proxies/alloy-receiver.alloy
- charts/k8s-monitoring/docs/examples/proxies/output.yaml
- charts/k8s-monitoring/tests/integration/auto-instrumentation/.rendered/output.yaml
- charts/k8s-monitoring/tests/integration/split-destinations/.rendered/output.yaml
- charts/k8s-monitoring/tests/platform/grafana-cloud/app-observability/.rendered/output.yaml
I'm sorry, I made a mistake in https://github.com/grafana/k8s-monitoring-helm/pull/1239, there are must be three `pod_association` instead of three `source` inside one `pod_association`. All `source` blocks has to match for the pod to be associated with a signal but we want it to be associated when one of the conditions is met (as in [Opentelemetry Collector chart](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/opentelemetry-collector-0.116.0/charts/opentelemetry-collector/templates/_config.tpl#L215)).
> fix: pod_association

- charts/k8s-monitoring/charts/feature-integrations/default-allow-lists/mimir.yaml
- charts/k8s-monitoring/charts/feature-integrations/default-allow-lists/tempo.yaml
This updates a typo `Loki` -> `Mimir` in a comment, and removes the TODO from the tempo metric names as the list has been populated.
> Fix typo and unnecessary TODO in comments

- charts/k8s-monitoring/templates/destinations/_destination_validations.tpl
- charts/k8s-monitoring/tests/destination_validations_test.yaml
Before, it would fail if you didn't specify a protocol, even though the default is "grpc" already.
> Fix Tempo validator's default check

- charts/k8s-monitoring/templates/platform_specific/openshift/alloy-profiles-scc.yaml
Mismatch caused pod creation to fail on OpenShift v4.18.1 with a security context constraint validation error.
* `values.yaml` had `alloy-profiles.controller.hostPID: true`, which conflicted with `allowHostPID: false` in the SCC.
* `alloy-profiles-scc.yaml` had `allowPrivilegedContainer: true`, which meant `allowPrivilegeEscalation: false` was not allowed.
> Update OpenShift SecurityContextConstraints for alloy-profiles to enable allowHostPID and allowPrivilegeEscalation

- charts/k8s-monitoring/docs/examples/service-integrations/mongodb-atlas/README.md
- charts/k8s-monitoring/docs/examples/service-integrations/mongodb-atlas/alloy-metrics.alloy
- charts/k8s-monitoring/docs/examples/service-integrations/mongodb-atlas/description.txt
- charts/k8s-monitoring/docs/examples/service-integrations/mongodb-atlas/output.yaml
- charts/k8s-monitoring/docs/examples/service-integrations/mongodb-atlas/values.yaml
To get metrics from a MongoDB Atlas (hosted) database, you first need to ask Mongo for the scrape URL.
This example shows how to implement `discovery.http` to do the remote service discovery.
> Add example for MongoDB Atlas, which is non-obvious

- charts/k8s-monitoring/docs/examples/extra-configuration/README.md
- charts/k8s-monitoring/docs/examples/extra-configuration/alloy-metrics.alloy
- charts/k8s-monitoring/docs/examples/extra-configuration/output.yaml
- charts/k8s-monitoring/docs/examples/extra-configuration/values.yaml
Because label seletors are a string, not an array
> Fix extra config example.

- charts/k8s-monitoring/README.md
- charts/k8s-monitoring/templates/collectors/_collector_remoteConfig.tpl
- charts/k8s-monitoring/values.schema.json
- charts/k8s-monitoring/values.yaml
`proxyURL` is specified in the [schema](https://github.com/grafana/k8s-monitoring-helm/blob/8075584af7292ec5248877aede16bf28edef9044/charts/k8s-monitoring/values.schema.json), but the field is not honored when specified. Hence fixed the bug.
> The proxyURL is not honored by the k8s-monitoring helm template.

- charts/k8s-monitoring/destinations/prometheus-values.yaml
- charts/k8s-monitoring/docs/destinations/prometheus.md
From [slack convo](https://raintank-corp.slack.com/archives/C06S3NJLA4W/p1743541145619669), added more explanation to distinguish between url and urlFrom
> For K8s Helm documentation, add explanation for urlFrom

- charts/k8s-monitoring/charts/feature-cluster-metrics/templates/_notes.tpl
- charts/k8s-monitoring/tests/integration/auth/.rendered/output.yaml
when all clusterMetrics components are managed outside of this helm chart (`deploy: false`), the `self-reporting-metric.prom` snippet includes a label value `deployments="%!s(<nil>)"`.\
This PR checks whether there are deployments managed by this chart and only then creates the label.
> Drop deployemnt label for clusterMetrics when no component is managed by helmchart

- charts/k8s-monitoring/docs/examples/features/application-observability/tail-sampling/README.md
- charts/k8s-monitoring/docs/examples/features/application-observability/tail-sampling/alloy-receiver.alloy
- charts/k8s-monitoring/docs/examples/features/application-observability/tail-sampling/description.txt
- charts/k8s-monitoring/docs/examples/features/application-observability/tail-sampling/output.yaml
- charts/k8s-monitoring/docs/examples/features/application-observability/tail-sampling/values.yaml
Add app o11y feature + tail sampling example
> tail sampling example

- charts/k8s-monitoring/docs/examples/platforms/openshift/output.yaml
- charts/k8s-monitoring/templates/platform_specific/openshift/alloy-logs-scc.yaml
- charts/k8s-monitoring/tests/platform/openshift/.rendered/output.yaml
The current scc for alloy logs in openshift renders the scc with hostpath first in the array. But it seems openshift reorders this upon apply. But this causes gitops systems to detect a diff and causes a lot of unecessary syncs.
This is similar to how the scc looks for `charts/k8s-monitoring-v1/templates/platform_specific/openshift/alloy-scc.yaml`, so I assume this was the case there as well.
> Fix infinite diff in openshift alloy logs scc

- charts/k8s-monitoring/tests/integration/upgrade/patch/.rendered/output.yaml
- charts/k8s-monitoring/tests/integration/upgrade/patch/deploy.sh
- charts/k8s-monitoring/tests/integration/upgrade/patch/deployments/grafana.yaml
- charts/k8s-monitoring/tests/integration/upgrade/patch/deployments/loki.yaml
- charts/k8s-monitoring/tests/integration/upgrade/patch/deployments/prometheus.yaml
- charts/k8s-monitoring/tests/integration/upgrade/patch/deployments/query-test.yaml
- charts/k8s-monitoring/tests/integration/upgrade/patch/values.yaml
- scripts/run-cluster-test.sh
* Install first at x.y.(z-1)
* Test for data (which blocks until data is available)
* Upgrade to x.y.z
* Test again
The chart sets a `chart_version` label to all metrics and logs with the current Helm chart version. This is how we ensure the upgrade was successful.
Successful run: https://github.com/grafana/k8s-monitoring-helm/actions/runs/14484180399/job/40626674396
> Add a test to check upgrades at the patch level

- charts/k8s-monitoring/charts/feature-cluster-metrics/templates/_validation.tpl
- charts/k8s-monitoring/charts/feature-cluster-metrics/templates/configmap.yaml
- charts/k8s-monitoring/charts/feature-cluster-metrics/tests/validation_test.yaml
- charts/k8s-monitoring/templates/features/_feature_cluster_metrics.tpl
If we have something like:
```
clusterMetrics:
windows-exporter:
enabled: false
```
but don't know that this will still deploy windows exporter, it can be surprising to see the daemonset still appear.
This adds a validation that checks if you want to add:
```
clusterMetrics:
windows-exporter:
enabled: false
deploy: false
```
> Add validation to warn against enabled: false and deploy: true

- charts/k8s-monitoring/charts/feature-annotation-autodiscovery/README.md
- charts/k8s-monitoring/charts/feature-annotation-autodiscovery/README.md.gotmpl
- charts/k8s-monitoring/charts/feature-application-observability/README.md
- charts/k8s-monitoring/charts/feature-application-observability/README.md.gotmpl
- charts/k8s-monitoring/charts/feature-auto-instrumentation/README.md
- charts/k8s-monitoring/charts/feature-auto-instrumentation/README.md.gotmpl
- charts/k8s-monitoring/charts/feature-cluster-events/README.md
- charts/k8s-monitoring/charts/feature-cluster-events/README.md.gotmpl
- charts/k8s-monitoring/charts/feature-cluster-metrics/README.md
- charts/k8s-monitoring/charts/feature-cluster-metrics/README.md.gotmpl
- charts/k8s-monitoring/charts/feature-node-logs/README.md
- charts/k8s-monitoring/charts/feature-node-logs/README.md.gotmpl
- charts/k8s-monitoring/charts/feature-pod-logs/README.md
- charts/k8s-monitoring/charts/feature-pod-logs/README.md.gotmpl
- charts/k8s-monitoring/charts/feature-profiling/README.md
- charts/k8s-monitoring/charts/feature-profiling/README.md.gotmpl
- charts/k8s-monitoring/charts/feature-prometheus-operator-objects/README.md
- charts/k8s-monitoring/charts/feature-prometheus-operator-objects/README.md.gotmpl
Just add the top-level element to the doc so you do't have to go back to the main README
> Adding usage section to feature docs

- .github/workflows/platform-test.yml
- charts/k8s-monitoring/tests/platform/aks/.envrc
- charts/k8s-monitoring/tests/platform/aks/.gitignore
- charts/k8s-monitoring/tests/platform/aks/.manual-only
- charts/k8s-monitoring/tests/platform/aks/.rendered/output.yaml
- charts/k8s-monitoring/tests/platform/aks/Makefile
- charts/k8s-monitoring/tests/platform/aks/aks-cluster-config.yaml
- charts/k8s-monitoring/tests/platform/aks/deployments/query-test.yaml
- charts/k8s-monitoring/tests/platform/aks/values.yaml
- scripts/includes/cluster/aks.sh
- scripts/includes/cluster/eks.sh
- scripts/run-cluster-test.sh
This only works locally for now because we don't have a shared service account for automated testing.
> Azure AKS Platform tests

- charts/k8s-monitoring/templates/_crd-validation.tpl
The links to download the CRD in the validation error responses are invalid. The GitHub releases are prefixed with a `v`, whereas the chart version var does not contain those.
> Fix CRD download link 

- charts/k8s-monitoring/docs/examples/auth/bearer-token/output.yaml
- charts/k8s-monitoring/docs/examples/auth/embedded-secrets/output.yaml
- charts/k8s-monitoring/docs/examples/auth/external-secrets/output.yaml
- charts/k8s-monitoring/docs/examples/exclude-by-namespace/output.yaml
- charts/k8s-monitoring/docs/examples/features/application-observability/default/output.yaml
- charts/k8s-monitoring/docs/examples/features/application-observability/tail-sampling/output.yaml
- charts/k8s-monitoring/docs/examples/features/auto-instrumentation/beyla-metrics-and-traces/output.yaml
- charts/k8s-monitoring/docs/examples/include-by-namespace/output.yaml
- charts/k8s-monitoring/docs/examples/meta-monitoring/output.yaml
- charts/k8s-monitoring/docs/examples/pod-labels-and-annotations/output.yaml
- charts/k8s-monitoring/docs/examples/proxies/output.yaml
- charts/k8s-monitoring/templates/alloy.yaml
- charts/k8s-monitoring/templates/collectors/_collector_helpers.tpl
- charts/k8s-monitoring/tests/integration/application-observability/.rendered/output.yaml
- charts/k8s-monitoring/tests/integration/application-observability/deployments/alloy-via-extra-service.yaml
- charts/k8s-monitoring/tests/integration/application-observability/deployments/query-test.yaml
- charts/k8s-monitoring/tests/integration/application-observability/values.yaml
- charts/k8s-monitoring/tests/integration/auto-instrumentation/.rendered/output.yaml
- charts/k8s-monitoring/tests/integration/prom-and-loki-to-otlp/deployments/prometheus.yaml
- charts/k8s-monitoring/tests/integration/proxies/.rendered/output.yaml
- charts/k8s-monitoring/tests/integration/split-destinations/.rendered/output.yaml
- charts/k8s-monitoring/tests/integration/statsd/.rendered/output.yaml
- charts/k8s-monitoring/tests/integration/tail-sampling/.rendered/output.yaml
- charts/k8s-monitoring/tests/platform/grafana-cloud/app-observability/.rendered/output.yaml
- charts/k8s-monitoring/tests/receiver-service_test.yaml
Three main changes:
1. Remove `extraService` from `kind: Alloy` objects, since that's defined in the K8s Monitoring Chart, not in Alloy.
2. Fix the label selectors for the extra service so it matches the labels assigned to alloy-receiver.
3. Update the unit and integration tests to validate these changes.
> Fix the label selectors for the extra receiver service

- charts/k8s-monitoring/tests/integration/alternative-deployments/argocd/Makefile
- charts/k8s-monitoring/tests/integration/auth/Makefile
- charts/k8s-monitoring/tests/integration/upgrade/minor/Makefile
- charts/k8s-monitoring/tests/integration/upgrade/minor/deploy.sh
- charts/k8s-monitoring/tests/integration/upgrade/patch/Makefile
- charts/k8s-monitoring/tests/integration/upgrade/patch/deploy.sh
- charts/k8s-monitoring/tests/platform/aks/Makefile
- charts/k8s-monitoring/tests/platform/eks-addon-with-terraform/Makefile
- charts/k8s-monitoring/tests/platform/eks-addon/Makefile
- charts/k8s-monitoring/tests/platform/eks-fargate/Makefile
- charts/k8s-monitoring/tests/platform/eks-with-windows/Makefile
- charts/k8s-monitoring/tests/platform/gke-autopilot/Makefile
- charts/k8s-monitoring/tests/platform/gke/Makefile
- charts/k8s-monitoring/tests/platform/grafana-cloud/app-observability/Makefile
- charts/k8s-monitoring/tests/platform/grafana-cloud/k8s-monitoring/Makefile
- charts/k8s-monitoring/tests/platform/openshift/Makefile
- charts/k8s-monitoring/tests/platform/otlp-gateway/Makefile
- charts/k8s-monitoring/tests/platform/remote-config/Makefile
- scripts/run-cluster-test.sh
Introduce a 'make check' for integration and platform tests that contain Makefiles. This target checks if the test is capable of running. A return code of 0 means the test can run. 1 means the test cannot run and is a failure. 2 means the test should be skipped.
> Skip upgrade tests if not applicable.

- charts/k8s-monitoring/docs/Collectors.md
- charts/k8s-monitoring/docs/Features.md
- charts/k8s-monitoring/docs/Migration.md
- charts/k8s-monitoring/docs/Structure.md
- charts/k8s-monitoring/docs/TargetingDataCollection.md
Performed following updates:
- Style and format changes in prep for moving HC docs into public docs
- Edits for clarity or any errors
- Updates due to Alloy Operator addition, including diagram (Please verify all changes related to this.  For example "Because collectors are deployed using the Alloy Operator, you can use any of the
standard [Alloy helm chart values](https://raw.githubusercontent.com/grafana/alloy/refs/heads/main/operations/helm/charts/alloy/values.yaml). These values will be used when creating the Alloy instance.")
Comments/questions for reviewers:
- Should the migration guide now be from 1x+ to 3? I was under the understanding that there are no incremental upgrades.
- Some content removed that referred to singleton not being automatically created since no instances are …
> K8s Helm chart docs update

- charts/k8s-monitoring/charts/feature-pod-logs/templates/_filelog.alloy.tpl
- charts/k8s-monitoring/charts/feature-pod-logs/tests/__snapshot__/filelog_test.yaml.snap
- charts/k8s-monitoring/charts/feature-pod-logs/tests/__snapshot__/kubernetesApi_test.yaml.snap
- charts/k8s-monitoring/charts/feature-pod-logs/tests/filelog_test.yaml
- charts/k8s-monitoring/charts/feature-pod-logs/tests/kubernetesApi_test.yaml
- charts/k8s-monitoring/tests/integration/pod-logs/filelog/.rendered/output.yaml
The `log.file.path` appears to be a log attribute, not a resource attribute, so we need to drop it in that context.
Also adds unit tests.
> Properly drop log.file.path from the log context

- charts/k8s-monitoring/tests/integration/application-observability/deployments/grafana.yaml
- charts/k8s-monitoring/tests/integration/auto-instrumentation/deployments/grafana.yaml
- charts/k8s-monitoring/tests/integration/istio-service-mesh/deployments/grafana.yaml
- charts/k8s-monitoring/tests/integration/proxies/deployments/grafana.yaml
- charts/k8s-monitoring/tests/integration/service-graph-metrics/deployments/grafana.yaml
- charts/k8s-monitoring/tests/integration/service-graph-metrics/deployments/query-test.yaml
- charts/k8s-monitoring/tests/integration/split-destinations/deployments/grafana.yaml
- charts/k8s-monitoring/tests/integration/tail-sampling/deployments/grafana.yaml
Default port for tempo helm chart changed from 3100 to 3200. Pulling the latest broke datasource connectivity in my test environment.
See https://github.com/grafana/helm-charts/pull/3745
> update tempo datasource port in integration tests

- charts/k8s-monitoring/templates/_crd-validation.tpl
Removes the empty double quote that breaks the Helm chart when `alloy-operator.deploy` is set to `false` to avoid error
```
executing "crdValidation" at <append>: wrong number of args for append: want 2 got 3
```
> fix(crd-validation): 🐛 remove bad double quote in crd validation

- charts/k8s-monitoring/charts/feature-application-observability/templates/_connector_span_metrics.tpl
- charts/k8s-monitoring/tests/integration/application-observability/.rendered/output.yaml
Beyla adds `span.metrics.skip` as span attribute, but for any changes supporting both resource and span attributes would make sense
> fix(spanmetrics): add span attribute support for skip metrics generation

- charts/k8s-monitoring/charts/feature-application-observability/README.md
- charts/k8s-monitoring/charts/feature-application-observability/templates/_processor_k8sattributes.tpl
- charts/k8s-monitoring/charts/feature-application-observability/tests/__snapshot__/default_test.yaml.snap
- charts/k8s-monitoring/charts/feature-application-observability/tests/__snapshot__/interval_test.yaml.snap
- charts/k8s-monitoring/charts/feature-application-observability/tests/__snapshot__/jaeger_test.yaml.snap
- charts/k8s-monitoring/charts/feature-application-observability/tests/__snapshot__/keepalive-settings_test.yaml.snap
- charts/k8s-monitoring/charts/feature-application-observability/tests/__snapshot__/memorylimiter_test.yaml.snap
- charts/k8s-monitoring/charts/feature-application-observability/tests/__snapshot__/resourcedetection_test.yaml.snap
- charts/k8s-monitoring/charts/feature-application-observability/tests/__snapshot__/spanlogs_test.yaml.snap
- charts/k8s-monitoring/charts/feature-application-observability/tests/__snapshot__/spanmetrics_test.yaml.snap
- charts/k8s-monitoring/charts/feature-application-observability/values.schema.json
- charts/k8s-monitoring/charts/feature-application-observability/values.yaml
Allow setting `passthrough` for the `k8sattributes` processor.
Refs: #1884
> chore: allow settings `passthrough` for k8sattributes processor

- charts/k8s-monitoring/charts/feature-integrations/docs/integrations/mysql.md
- charts/k8s-monitoring/charts/feature-integrations/integrations/mysql-values.yaml
- charts/k8s-monitoring/charts/feature-integrations/schema-mods/definitions/mysql-integration.schema.json
- charts/k8s-monitoring/charts/feature-integrations/templates/_integration_mysql_metrics.tpl
- charts/k8s-monitoring/charts/feature-integrations/values.schema.json
- charts/k8s-monitoring/docs/examples/features/integrations/multiple/alloy-metrics.alloy
- charts/k8s-monitoring/docs/examples/features/integrations/multiple/output.yaml
- charts/k8s-monitoring/docs/examples/features/integrations/mysql/alloy-metrics.alloy
- charts/k8s-monitoring/docs/examples/features/integrations/mysql/output.yaml
- charts/k8s-monitoring/tests/integration/service-integrations/mysql/.rendered/output.yaml
The issue is that `prometheus.exporter.mysql` already sets the `job` label.
`prometheus.scrape`'s `job_label` field will only set the label if it's not already set, which means we can't overwrite the label. We need to move that into the `prometheus.relabel` component.
> Fix job label issue and add the ability to set rules
